REM INSERTING into IDU_BENEF_UT
SET DEFINE OFF;
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,'Id dos beneficios do utente');
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SCG_TIPOBENEF_ID','NUMBER','No',null,2,'Id do tipo de Beneficio');
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('IDU_BENEF_REGRAS_ID','NUMBER','Yes',null,3,'Id da regra a aplicar ao beneficio');
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('COD_BENEF','VARCHAR2(5 CHAR)','No',null,4,null);
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DESCR','VARCHAR2(240 CHAR)','Yes',null,5,null);
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DESCR_ABREV','VARCHAR2(40 CHAR)','Yes',null,6,null);
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('FUND_LEGAL','VARCHAR2(100 CHAR)','Yes',null,7,null);
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CARTAO','VARCHAR2(1 CHAR)','Yes','''S''',8,null);
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 CHAR)','No',null,9,'Coluna de audit.');
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','No',null,10,'Coluna de audit.');
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 CHAR)','No',null,11,'Coluna de audit.');
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','No',null,12,'Coluna de audit.');
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ACTIVO','VARCHAR2(1 BYTE)','No','''S'' ',13,null);
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DATA_INICIO','DATE','No',null,14,null);
Insert into IDU_BENEF_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DATA_FIM','DATE','Yes',null,15,null);
