REM INSERTING into IDU_INSCR
SET DEFINE OFF;
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,'Id da inscric?o');
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('IDU_IDENT_UT_ID','NUMBER','No',null,2,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DTA_INSC','DATE','No',null,3,'Data da inscric?o do utente no centro de saude.');
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SCG_TIPOUTENTE_ID','NUMBER','No',null,4,'Id do codigo de tipo de utente');
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SCG_TIPOINSCR_ID','NUMBER','No',null,5,'Id do tipo de inscric?o do utente');
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SYS_ENTIDADES_ID','NUMBER','No',null,6,'Id da entidade (centro)');
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DATA_INI','DATE','No',null,7,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DATA_FIM','DATE','Yes',null,8,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 CHAR)','No',null,9,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','No',null,10,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 CHAR)','No',null,11,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','No',null,12,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('IDU_IDENT_UT_DUP_ID','NUMBER','Yes',null,13,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SINC_DATE','DATE','Yes',null,14,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SINC_DML_ID','NUMBER','Yes',null,15,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SCG_MOTIVO_FECHO_ID','NUMBER','Yes',null,16,null);
Insert into IDU_INSCR (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SYS_ENTIDADES_ID_MATERNIDADE','NUMBER','Yes',null,17,null);
