REM INSERTING into IDU_HIST_BENEF
SET DEFINE OFF;
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('IDU_IDENT_UT_ID','NUMBER','No',null,2,'Id do utente');
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('IDU_BENEF_UT_ID','NUMBER','No',null,3,'Id do Beneficio');
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('NDOC_ISENT','NUMBER(6,0)','Yes',null,4,'Arquivo das provas de Isenção');
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DTA_VALIDADE','DATE','Yes',null,5,'Data fim da validade do beneficio');
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DATA_INI','DATE','Yes',null,6,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('DATA_FIM','DATE','Yes',null,7,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 CHAR)','No',null,8,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 CHAR)','No',null,9,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','No',null,10,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','No',null,11,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SINC_DATE','DATE','Yes',null,12,null);
Insert into IDU_HIST_BENEF (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SINC_DML_ID','NUMBER','Yes',null,13,null);
