REM INSERTING into IDU_CONTACTOS_UT
SET DEFINE OFF;
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,'Id do contacto do utente');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('IDU_IDENT_UT_ID','NUMBER','No',null,2,'Id do utente');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('NOME_CONTACTO','VARCHAR2(150 CHAR)','Yes',null,3,'Nome do Contacto do utente');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('TELF_CONTACTO','VARCHAR2(20 CHAR)','Yes',null,4,'Telefone do contacto do utente');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('TELM_CONTACTO','VARCHAR2(20 CHAR)','Yes',null,5,'Telemovel de contacto do utente');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('OTIPO_CONTACTO','VARCHAR2(60 CHAR)','Yes',null,6,'Outro tipo de contacto associado ao utente');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('NO_OTIPO_CONTACTO','VARCHAR2(100 CHAR)','Yes',null,7,'Nº (ou endereço caso tipo de contacto = EMAIL) de outro tipo de contacto.');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('OBS','VARCHAR2(150 CHAR)','Yes',null,8,'Observações do contacto');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 CHAR)','No',null,9,'Coluna de audit');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','No',null,10,'Coluna de audit');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 CHAR)','No',null,11,'Coluna de audit');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','No',null,12,'Coluna de audit');
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SINC_DATE','DATE','Yes',null,13,null);
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SINC_DML_ID','NUMBER','Yes',null,14,null);
Insert into IDU_CONTACTOS_UT (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('EMAIL_CONTACTO','VARCHAR2(100 CHAR)','Yes',null,15,null);
