REM INSERTING into SYS_PERFIS
SET DEFINE OFF;
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,null);
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('PERFIL','NUMBER(10,0)','No',null,2,'Codigo do perfil.');
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('PAPEL','VARCHAR2(30 BYTE)','No',null,3,'Designac?o do perfil.');
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('MC','NUMBER(1,0)','Yes',null,4,'Tipo de perfil oracle.');
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 BYTE)','No',null,5,null);
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','No',null,6,null);
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 BYTE)','No',null,7,null);
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','No',null,8,null);
Insert into SYS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID_APP','NUMBER','Yes',null,9,null);
