REM INSERTING into SYS_USERS_PERFIS
SET DEFINE OFF;
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,null);
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SYS_USERS_ID','NUMBER','No',null,2,null);
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SYS_PERFIS_ID','NUMBER','No',null,3,null);
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SYS_ENTIDADES_ID','NUMBER','Yes',null,4,null);
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 BYTE)','No',null,5,null);
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','No',null,6,null);
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 BYTE)','No',null,7,null);
Insert into SYS_USERS_PERFIS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','No',null,8,null);
