REM INSERTING into SYS_USERS
SET DEFINE OFF;
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('NUM_MECANOG','NUMBER(6,0)','Yes',null,2,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('NOME','VARCHAR2(50 CHAR)','No',null,3,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('SENHA','VARCHAR2(30 CHAR)','Yes',null,4,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ACTIVO','VARCHAR2(1 CHAR)','No','''S'' ',5,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 CHAR)','No',null,6,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','No',null,7,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 CHAR)','No',null,8,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','No',null,9,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('PRO_PROFISSID_PESSOAL_ID','NUMBER','Yes',null,10,null);
Insert into SYS_USERS (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ALTERAR_PASS','VARCHAR2(1 CHAR)','Yes','''S''',11,null);
