REM INSERTING into SYS_OPCOES_MENU
SET DEFINE OFF;
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER','No',null,1,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('NOME','VARCHAR2(10 BYTE)','No',null,2,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('PROMPT','VARCHAR2(30 CHAR)','No',null,3,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('TIPO','VARCHAR2(1 BYTE)','No',null,4,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('URL','VARCHAR2(100 BYTE)','Yes',null,5,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATED_BY','VARCHAR2(30 BYTE)','Yes',null,6,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('CREATION_DATE','DATE','Yes',null,7,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATED_BY','VARCHAR2(30 BYTE)','Yes',null,8,null);
Insert into SYS_OPCOES_MENU (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('LAST_UPDATE_DATE','DATE','Yes',null,9,null);
