package ora.pt.cons.igif.sics.baixas;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import ora.pt.cons.igif.sics.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BaixaViewImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public BaixaViewImpl() {
    }
   
}
