package ora.pt.cons.igif.sics.suporte;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodigoGenericoImpl extends EntityImpl {
    public static final int ID = 0;
    public static final int ACTIVO = 1;
    public static final int CODIGO = 2;
    public static final int CODIGOANTIGO = 3;
    public static final int DATAACTIVO = 4;
    public static final int DATAINACTIVO = 5;
    public static final int DESCRICAO = 6;
    public static final int DESCABRV = 7;
    public static final int LIMITEMAX = 8;
    public static final int LIMITEMIN = 9;
    public static final int OBSERVACOES = 10;
    public static final int ORDENACAO = 11;
    public static final int SYSENTIDADESID = 12;
    public static final int SYSTIPOSCODIGOSID = 13;
    public static final int CREATEDBY = 14;
    public static final int CREATIONDATE = 15;
    public static final int LASTUPDATEDBY = 16;
    public static final int LASTUPDATEDATE = 17;
    public static final int TIPOCODIGO = 18;
    public static final int CODIGOHIERARQUICO = 19;
    public static final int ENTIDADE = 20;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public CodigoGenericoImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("ora.pt.cons.igif.sics.suporte.CodigoGenerico");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for Activo, using the alias name Activo
     */
    public String getActivo() {
        return (String)getAttributeInternal(ACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for Activo
     */
    public void setActivo(String value) {
        setAttributeInternal(ACTIVO, value);
    }

    /**Gets the attribute value for Codigo, using the alias name Codigo
     */
    public String getCodigo() {
        return (String)getAttributeInternal(CODIGO);
    }

    /**Sets <code>value</code> as the attribute value for Codigo
     */
    public void setCodigo(String value) {
        setAttributeInternal(CODIGO, value);
    }

    /**Gets the attribute value for CodigoAntigo, using the alias name CodigoAntigo
     */
    public String getCodigoAntigo() {
        return (String)getAttributeInternal(CODIGOANTIGO);
    }

    /**Sets <code>value</code> as the attribute value for CodigoAntigo
     */
    public void setCodigoAntigo(String value) {
        setAttributeInternal(CODIGOANTIGO, value);
    }

    /**Gets the attribute value for DataActivo, using the alias name DataActivo
     */
    public Date getDataActivo() {
        return (Date)getAttributeInternal(DATAACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for DataActivo
     */
    public void setDataActivo(Date value) {
        setAttributeInternal(DATAACTIVO, value);
    }

    /**Gets the attribute value for DataInactivo, using the alias name DataInactivo
     */
    public Date getDataInactivo() {
        return (Date)getAttributeInternal(DATAINACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for DataInactivo
     */
    public void setDataInactivo(Date value) {
        setAttributeInternal(DATAINACTIVO, value);
    }

    /**Gets the attribute value for Descricao, using the alias name Descricao
     */
    public String getDescricao() {
        return (String)getAttributeInternal(DESCRICAO);
    }

    /**Sets <code>value</code> as the attribute value for Descricao
     */
    public void setDescricao(String value) {
        setAttributeInternal(DESCRICAO, value);
    }

    /**Gets the attribute value for DescAbrv, using the alias name DescAbrv
     */
    public String getDescAbrv() {
        return (String)getAttributeInternal(DESCABRV);
    }

    /**Sets <code>value</code> as the attribute value for DescAbrv
     */
    public void setDescAbrv(String value) {
        setAttributeInternal(DESCABRV, value);
    }

    /**Gets the attribute value for LimiteMax, using the alias name LimiteMax
     */
    public Number getLimiteMax() {
        return (Number)getAttributeInternal(LIMITEMAX);
    }

    /**Sets <code>value</code> as the attribute value for LimiteMax
     */
    public void setLimiteMax(Number value) {
        setAttributeInternal(LIMITEMAX, value);
    }

    /**Gets the attribute value for LimiteMin, using the alias name LimiteMin
     */
    public Number getLimiteMin() {
        return (Number)getAttributeInternal(LIMITEMIN);
    }

    /**Sets <code>value</code> as the attribute value for LimiteMin
     */
    public void setLimiteMin(Number value) {
        setAttributeInternal(LIMITEMIN, value);
    }

    /**Gets the attribute value for Observacoes, using the alias name Observacoes
     */
    public String getObservacoes() {
        return (String)getAttributeInternal(OBSERVACOES);
    }

    /**Sets <code>value</code> as the attribute value for Observacoes
     */
    public void setObservacoes(String value) {
        setAttributeInternal(OBSERVACOES, value);
    }

    /**Gets the attribute value for Ordenacao, using the alias name Ordenacao
     */
    public Number getOrdenacao() {
        return (Number)getAttributeInternal(ORDENACAO);
    }

    /**Sets <code>value</code> as the attribute value for Ordenacao
     */
    public void setOrdenacao(Number value) {
        setAttributeInternal(ORDENACAO, value);
    }

    /**Gets the attribute value for SysEntidadesId, using the alias name SysEntidadesId
     */
    public Number getSysEntidadesId() {
        return (Number)getAttributeInternal(SYSENTIDADESID);
    }

    /**Sets <code>value</code> as the attribute value for SysEntidadesId
     */
    public void setSysEntidadesId(Number value) {
        setAttributeInternal(SYSENTIDADESID, value);
    }

    /**Gets the attribute value for SysTiposCodigosId, using the alias name SysTiposCodigosId
     */
    public Number getSysTiposCodigosId() {
        return (Number)getAttributeInternal(SYSTIPOSCODIGOSID);
    }

    /**Sets <code>value</code> as the attribute value for SysTiposCodigosId
     */
    public void setSysTiposCodigosId(Number value) {
        setAttributeInternal(SYSTIPOSCODIGOSID, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case ACTIVO:
            return getActivo();
        case CODIGO:
            return getCodigo();
        case CODIGOANTIGO:
            return getCodigoAntigo();
        case DATAACTIVO:
            return getDataActivo();
        case DATAINACTIVO:
            return getDataInactivo();
        case DESCRICAO:
            return getDescricao();
        case DESCABRV:
            return getDescAbrv();
        case LIMITEMAX:
            return getLimiteMax();
        case LIMITEMIN:
            return getLimiteMin();
        case OBSERVACOES:
            return getObservacoes();
        case ORDENACAO:
            return getOrdenacao();
        case SYSENTIDADESID:
            return getSysEntidadesId();
        case SYSTIPOSCODIGOSID:
            return getSysTiposCodigosId();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case CODIGOHIERARQUICO:
            return getCodigoHierarquico();
        case TIPOCODIGO:
            return getTipoCodigo();
        case ENTIDADE:
            return getEntidade();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((DBSequence)value);
            return;
        case ACTIVO:
            setActivo((String)value);
            return;
        case CODIGO:
            setCodigo((String)value);
            return;
        case CODIGOANTIGO:
            setCodigoAntigo((String)value);
            return;
        case DATAACTIVO:
            setDataActivo((Date)value);
            return;
        case DATAINACTIVO:
            setDataInactivo((Date)value);
            return;
        case DESCRICAO:
            setDescricao((String)value);
            return;
        case DESCABRV:
            setDescAbrv((String)value);
            return;
        case LIMITEMAX:
            setLimiteMax((Number)value);
            return;
        case LIMITEMIN:
            setLimiteMin((Number)value);
            return;
        case OBSERVACOES:
            setObservacoes((String)value);
            return;
        case ORDENACAO:
            setOrdenacao((Number)value);
            return;
        case SYSENTIDADESID:
            setSysEntidadesId((Number)value);
            return;
        case SYSTIPOSCODIGOSID:
            setSysTiposCodigosId((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity TipoCodigoImpl
     */
    public TipoCodigoImpl getTipoCodigo() {
        return (TipoCodigoImpl)getAttributeInternal(TIPOCODIGO);
    }

    /**Sets <code>value</code> as the associated entity TipoCodigoImpl
     */
    public void setTipoCodigo(TipoCodigoImpl value) {
        setAttributeInternal(TIPOCODIGO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getCodigoHierarquico() {
        return (RowIterator)getAttributeInternal(CODIGOHIERARQUICO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public EntidadeImpl getEntidade() {
        return (EntidadeImpl)getAttributeInternal(ENTIDADE);
    }

    /**Sets <code>value</code> as the associated entity EntidadeImpl
     */
    public void setEntidade(EntidadeImpl value) {
        setAttributeInternal(ENTIDADE, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }
}
