package ora.pt.cons.igif.sics.suporte;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodigoHierarquicoImpl extends EntityImpl {
    public static final int ID = 0;
    public static final int ACTIVO = 1;
    public static final int CODIGO = 2;
    public static final int CODIGOANTIGO = 3;
    public static final int CODAUX01 = 4;
    public static final int CODAUX02 = 5;
    public static final int CODAUX03 = 6;
    public static final int CODAUX04 = 7;
    public static final int CODAUX05 = 8;
    public static final int DATAACTIVO = 9;
    public static final int DATAINACTIVO = 10;
    public static final int DESCRICAO = 11;
    public static final int DESCABRV = 12;
    public static final int OBSERVACOES = 13;
    public static final int SYSCODIGOPOSTALID = 14;
    public static final int SYSCODGENERICOSID = 15;
    public static final int SYSCODHIERID = 16;
    public static final int SYSTIPOSCODIGOSID = 17;
    public static final int CREATEDBY = 18;
    public static final int CREATIONDATE = 19;
    public static final int LASTUPDATEDBY = 20;
    public static final int LASTUPDATEDATE = 21;
    public static final int SYSCODHIERNUTID = 22;
    public static final int CODIGOGENERICO = 23;
    public static final int SYSCODHIERIDCODIGOHIERARQUICO = 24;
    public static final int CODIGOPOSTAL = 25;
    public static final int TIPOCODIGO = 26;
    public static final int SYSCODHIERNUTIDCODIGOHIERARQUICO = 27;
    public static final int CODIGOHIERARQUICO1 = 28;
    public static final int CODIGOHIERARQUICO = 29;
    public static final int ENTIDADE = 30;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public CodigoHierarquicoImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("ora.pt.cons.igif.sics.suporte.CodigoHierarquico");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for Activo, using the alias name Activo
     */
    public String getActivo() {
        return (String)getAttributeInternal(ACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for Activo
     */
    public void setActivo(String value) {
        setAttributeInternal(ACTIVO, value);
    }

    /**Gets the attribute value for Codigo, using the alias name Codigo
     */
    public String getCodigo() {
        return (String)getAttributeInternal(CODIGO);
    }

    /**Sets <code>value</code> as the attribute value for Codigo
     */
    public void setCodigo(String value) {
        setAttributeInternal(CODIGO, value);
    }

    /**Gets the attribute value for CodigoAntigo, using the alias name CodigoAntigo
     */
    public String getCodigoAntigo() {
        return (String)getAttributeInternal(CODIGOANTIGO);
    }

    /**Sets <code>value</code> as the attribute value for CodigoAntigo
     */
    public void setCodigoAntigo(String value) {
        setAttributeInternal(CODIGOANTIGO, value);
    }

    /**Gets the attribute value for CodAux01, using the alias name CodAux01
     */
    public String getCodAux01() {
        return (String)getAttributeInternal(CODAUX01);
    }

    /**Sets <code>value</code> as the attribute value for CodAux01
     */
    public void setCodAux01(String value) {
        setAttributeInternal(CODAUX01, value);
    }

    /**Gets the attribute value for CodAux02, using the alias name CodAux02
     */
    public String getCodAux02() {
        return (String)getAttributeInternal(CODAUX02);
    }

    /**Sets <code>value</code> as the attribute value for CodAux02
     */
    public void setCodAux02(String value) {
        setAttributeInternal(CODAUX02, value);
    }

    /**Gets the attribute value for CodAux03, using the alias name CodAux03
     */
    public String getCodAux03() {
        return (String)getAttributeInternal(CODAUX03);
    }

    /**Sets <code>value</code> as the attribute value for CodAux03
     */
    public void setCodAux03(String value) {
        setAttributeInternal(CODAUX03, value);
    }

    /**Gets the attribute value for CodAux04, using the alias name CodAux04
     */
    public String getCodAux04() {
        return (String)getAttributeInternal(CODAUX04);
    }

    /**Sets <code>value</code> as the attribute value for CodAux04
     */
    public void setCodAux04(String value) {
        setAttributeInternal(CODAUX04, value);
    }

    /**Gets the attribute value for CodAux05, using the alias name CodAux05
     */
    public String getCodAux05() {
        return (String)getAttributeInternal(CODAUX05);
    }

    /**Sets <code>value</code> as the attribute value for CodAux05
     */
    public void setCodAux05(String value) {
        setAttributeInternal(CODAUX05, value);
    }

    /**Gets the attribute value for DataActivo, using the alias name DataActivo
     */
    public Date getDataActivo() {
        return (Date)getAttributeInternal(DATAACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for DataActivo
     */
    public void setDataActivo(Date value) {
        setAttributeInternal(DATAACTIVO, value);
    }

    /**Gets the attribute value for DataInactivo, using the alias name DataInactivo
     */
    public Date getDataInactivo() {
        return (Date)getAttributeInternal(DATAINACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for DataInactivo
     */
    public void setDataInactivo(Date value) {
        setAttributeInternal(DATAINACTIVO, value);
    }

    /**Gets the attribute value for Descricao, using the alias name Descricao
     */
    public String getDescricao() {
        return (String)getAttributeInternal(DESCRICAO);
    }

    /**Sets <code>value</code> as the attribute value for Descricao
     */
    public void setDescricao(String value) {
        setAttributeInternal(DESCRICAO, value);
    }

    /**Gets the attribute value for DescAbrv, using the alias name DescAbrv
     */
    public String getDescAbrv() {
        return (String)getAttributeInternal(DESCABRV);
    }

    /**Sets <code>value</code> as the attribute value for DescAbrv
     */
    public void setDescAbrv(String value) {
        setAttributeInternal(DESCABRV, value);
    }

    /**Gets the attribute value for Observacoes, using the alias name Observacoes
     */
    public String getObservacoes() {
        return (String)getAttributeInternal(OBSERVACOES);
    }

    /**Sets <code>value</code> as the attribute value for Observacoes
     */
    public void setObservacoes(String value) {
        setAttributeInternal(OBSERVACOES, value);
    }

    /**Gets the attribute value for SysCodigoPostalId, using the alias name SysCodigoPostalId
     */
    public Number getSysCodigoPostalId() {
        return (Number)getAttributeInternal(SYSCODIGOPOSTALID);
    }

    /**Sets <code>value</code> as the attribute value for SysCodigoPostalId
     */
    public void setSysCodigoPostalId(Number value) {
        setAttributeInternal(SYSCODIGOPOSTALID, value);
    }

    /**Gets the attribute value for SysCodGenericosId, using the alias name SysCodGenericosId
     */
    public Number getSysCodGenericosId() {
        return (Number)getAttributeInternal(SYSCODGENERICOSID);
    }

    /**Sets <code>value</code> as the attribute value for SysCodGenericosId
     */
    public void setSysCodGenericosId(Number value) {
        setAttributeInternal(SYSCODGENERICOSID, value);
    }

    /**Gets the attribute value for SysCodHierId, using the alias name SysCodHierId
     */
    public Number getSysCodHierId() {
        return (Number)getAttributeInternal(SYSCODHIERID);
    }

    /**Sets <code>value</code> as the attribute value for SysCodHierId
     */
    public void setSysCodHierId(Number value) {
        setAttributeInternal(SYSCODHIERID, value);
    }

    /**Gets the attribute value for SysTiposCodigosId, using the alias name SysTiposCodigosId
     */
    public Number getSysTiposCodigosId() {
        return (Number)getAttributeInternal(SYSTIPOSCODIGOSID);
    }

    /**Sets <code>value</code> as the attribute value for SysTiposCodigosId
     */
    public void setSysTiposCodigosId(Number value) {
        setAttributeInternal(SYSTIPOSCODIGOSID, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case ACTIVO:
            return getActivo();
        case CODIGO:
            return getCodigo();
        case CODIGOANTIGO:
            return getCodigoAntigo();
        case CODAUX01:
            return getCodAux01();
        case CODAUX02:
            return getCodAux02();
        case CODAUX03:
            return getCodAux03();
        case CODAUX04:
            return getCodAux04();
        case CODAUX05:
            return getCodAux05();
        case DATAACTIVO:
            return getDataActivo();
        case DATAINACTIVO:
            return getDataInactivo();
        case DESCRICAO:
            return getDescricao();
        case DESCABRV:
            return getDescAbrv();
        case OBSERVACOES:
            return getObservacoes();
        case SYSCODIGOPOSTALID:
            return getSysCodigoPostalId();
        case SYSCODGENERICOSID:
            return getSysCodGenericosId();
        case SYSCODHIERID:
            return getSysCodHierId();
        case SYSTIPOSCODIGOSID:
            return getSysTiposCodigosId();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case SYSCODHIERNUTID:
            return getSysCodHierNutId();
        case CODIGOHIERARQUICO1:
            return getCodigoHierarquico1();
        case CODIGOHIERARQUICO:
            return getCodigoHierarquico();
        case ENTIDADE:
            return getEntidade();
        case TIPOCODIGO:
            return getTipoCodigo();
        case CODIGOPOSTAL:
            return getCodigoPostal();
        case SYSCODHIERNUTIDCODIGOHIERARQUICO:
            return getSysCodHierNutIdCodigoHierarquico();
        case SYSCODHIERIDCODIGOHIERARQUICO:
            return getSysCodHierIdCodigoHierarquico();
        case CODIGOGENERICO:
            return getCodigoGenerico();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((DBSequence)value);
            return;
        case ACTIVO:
            setActivo((String)value);
            return;
        case CODIGO:
            setCodigo((String)value);
            return;
        case CODIGOANTIGO:
            setCodigoAntigo((String)value);
            return;
        case CODAUX01:
            setCodAux01((String)value);
            return;
        case CODAUX02:
            setCodAux02((String)value);
            return;
        case CODAUX03:
            setCodAux03((String)value);
            return;
        case CODAUX04:
            setCodAux04((String)value);
            return;
        case CODAUX05:
            setCodAux05((String)value);
            return;
        case DATAACTIVO:
            setDataActivo((Date)value);
            return;
        case DATAINACTIVO:
            setDataInactivo((Date)value);
            return;
        case DESCRICAO:
            setDescricao((String)value);
            return;
        case DESCABRV:
            setDescAbrv((String)value);
            return;
        case OBSERVACOES:
            setObservacoes((String)value);
            return;
        case SYSCODIGOPOSTALID:
            setSysCodigoPostalId((Number)value);
            return;
        case SYSCODGENERICOSID:
            setSysCodGenericosId((Number)value);
            return;
        case SYSCODHIERID:
            setSysCodHierId((Number)value);
            return;
        case SYSTIPOSCODIGOSID:
            setSysTiposCodigosId((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case SYSCODHIERNUTID:
            setSysCodHierNutId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity CodigoGenericoImpl
     */
    public CodigoGenericoImpl getCodigoGenerico() {
        return (CodigoGenericoImpl)getAttributeInternal(CODIGOGENERICO);
    }

    /**Sets <code>value</code> as the associated entity CodigoGenericoImpl
     */
    public void setCodigoGenerico(CodigoGenericoImpl value) {
        setAttributeInternal(CODIGOGENERICO, value);
    }

    /**Gets the attribute value for SysCodHierNutId, using the alias name SysCodHierNutId
     */
    public Number getSysCodHierNutId() {
        return (Number)getAttributeInternal(SYSCODHIERNUTID);
    }

    /**Sets <code>value</code> as the attribute value for SysCodHierNutId
     */
    public void setSysCodHierNutId(Number value) {
        setAttributeInternal(SYSCODHIERNUTID, value);
    }

    /**Gets the associated entity CodigoHierarquicoImpl
     */
    public CodigoHierarquicoImpl getSysCodHierIdCodigoHierarquico() {
        return (CodigoHierarquicoImpl)getAttributeInternal(SYSCODHIERIDCODIGOHIERARQUICO);
    }

    /**Sets <code>value</code> as the associated entity CodigoHierarquicoImpl
     */
    public void setSysCodHierIdCodigoHierarquico(CodigoHierarquicoImpl value) {
        setAttributeInternal(SYSCODHIERIDCODIGOHIERARQUICO, value);
    }

    /**Gets the associated entity CodigoPostalImpl
     */
    public CodigoPostalImpl getCodigoPostal() {
        return (CodigoPostalImpl)getAttributeInternal(CODIGOPOSTAL);
    }

    /**Sets <code>value</code> as the associated entity CodigoPostalImpl
     */
    public void setCodigoPostal(CodigoPostalImpl value) {
        setAttributeInternal(CODIGOPOSTAL, value);
    }

    /**Gets the associated entity TipoCodigoImpl
     */
    public TipoCodigoImpl getTipoCodigo() {
        return (TipoCodigoImpl)getAttributeInternal(TIPOCODIGO);
    }

    /**Sets <code>value</code> as the associated entity TipoCodigoImpl
     */
    public void setTipoCodigo(TipoCodigoImpl value) {
        setAttributeInternal(TIPOCODIGO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getCodigoHierarquico() {
        return (RowIterator)getAttributeInternal(CODIGOHIERARQUICO);
    }

    /**Gets the associated entity CodigoHierarquicoImpl
     */
    public CodigoHierarquicoImpl getSysCodHierNutIdCodigoHierarquico() {
        return (CodigoHierarquicoImpl)getAttributeInternal(SYSCODHIERNUTIDCODIGOHIERARQUICO);
    }

    /**Sets <code>value</code> as the associated entity CodigoHierarquicoImpl
     */
    public void setSysCodHierNutIdCodigoHierarquico(CodigoHierarquicoImpl value) {
        setAttributeInternal(SYSCODHIERNUTIDCODIGOHIERARQUICO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getCodigoHierarquico1() {
        return (RowIterator)getAttributeInternal(CODIGOHIERARQUICO1);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getEntidade() {
        return (RowIterator)getAttributeInternal(ENTIDADE);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }
}
