package ora.pt.cons.igif.sics.utentes.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class DetalheUtenteRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "DataValCart_FMT_FORMAT", "dd-MM-yyyy" },
{ "MoradaEdificio_LABEL", "Edifício" },
{ "Telf_LABEL", "Telefone" },
{ "FreguesiaNat_LABEL", "Freguesia" },
{ "DataInscr_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataInscr_LABEL", "Data Inscrição" },
{ "MoradaFreguesia_LABEL", "Freguesia" },
{ "MoradaConcelho_LABEL", "Concelho" },
{ "DataValCart_LABEL", "Validade" },
{ "MoradaLugar_LABEL", "Lugar" },
{ "CentroSaude_LABEL", "Centro Saúde" },
{ "DistritoNat_LABEL", "Distrito" },
{ "NDocIdent_LABEL", "Nº Doc. Ident." },
{ "Nif_LABEL", "NIF" },
{ "MoradaRua_LABEL", "Rua" },
{ "Email_LABEL", "E-Mail" },
{ "BenefIsencaoDtaFim_LABEL", "Data Fim" },
{ "DataValCart_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "Niss_LABEL", "Nº S. S." },
{ "MoradaLocal_LABEL", "Localidade" },
{ "DataNasc_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "CPaisNat_LABEL", "País" },
{ "BenefIsencaoDtaIni_LABEL", "Data Início" },
{ "ConcelhoNat_LABEL", "Concelho" },
{ "DataNasc_FMT_FORMAT", "dd-MM-yyyy" },
{ "BenefRecmDtaIni_LABEL", "Data Início" },
{ "TipoBi_LABEL", "Doc. Ident." },
{ "MoradaVia_LABEL", "Via" },
{ "NumBenef_LABEL", "Nº Benef." },
{ "BenefRecmDtaFim_LABEL", "Data Fim" },
{ "DescTpInscr_LABEL", "T. Inscrição" },
{ "DataInscr_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "NumMedico_LABEL", "Médico" },
{ "EntResp_LABEL", "Ent. Resp." },
{ "DataNasc_LABEL", "Data de Nasc." },
{ "IdiId_LABEL", "Utente" },
{ "BenefIsencaoDescr_LABEL", "Isenção Tx. M." },
{ "CodPostal1_LABEL", "Código Postal" },
{ "Nacionalidade_LABEL", "Nacionalidade" },
{ "MoradaPorta_LABEL", "Porta" },
{ "BenefRecmDescr_LABEL", "RECM" },
{ "CodPostalLocal_LABEL", "Local Postal" },
{ "MoradaDistrito_LABEL", "Distrito" },
{ "Sexo_LABEL", "Sexo" }};

    /**
     * This is the default constructor (do not remove)
     */
    public DetalheUtenteRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
