package ora.pt.cons.igif.sics.suporte;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntidadeImpl extends EntityImpl {
    public static final int ID = 0;
    public static final int ACTIVO = 1;
    public static final int CODIGO = 2;
    public static final int CODIGOANTIGO = 3;
    public static final int CODAUX01 = 4;
    public static final int CODAUX02 = 5;
    public static final int CODAUX03 = 6;
    public static final int CODAUX04 = 7;
    public static final int CODAUX05 = 8;
    public static final int DATAACTIVO = 9;
    public static final int DATAINACTIVO = 10;
    public static final int DESCABRV = 11;
    public static final int DESIGNACAO = 12;
    public static final int MORADA = 13;
    public static final int PATHIMAGEM = 14;
    public static final int SYSENTIDADESID = 15;
    public static final int SYSSUBTIPOENTIDADESID = 16;
    public static final int SYSTIPOSCODIGOSID = 17;
    public static final int TELEFONE = 18;
    public static final int URL = 19;
    public static final int CREATEDBY = 20;
    public static final int CREATIONDATE = 21;
    public static final int LASTUPDATEDBY = 22;
    public static final int LASTUPDATEDATE = 23;
    public static final int SYSCODHIERID = 24;
    public static final int SYSCODIGOPOSTALID = 25;
    public static final int CODIGOGENERICO = 26;
    public static final int SYSENTIDADESIDENTIDADE = 27;
    public static final int TIPOCODIGO = 28;
    public static final int FERIADO = 29;
    public static final int ENTIDADE = 30;
    public static final int CODIGOHIERARQUICO = 31;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public EntidadeImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("ora.pt.cons.igif.sics.suporte.Entidade");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for Activo, using the alias name Activo
     */
    public String getActivo() {
        return (String)getAttributeInternal(ACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for Activo
     */
    public void setActivo(String value) {
        setAttributeInternal(ACTIVO, value);
    }

    /**Gets the attribute value for Codigo, using the alias name Codigo
     */
    public Number getCodigo() {
        return (Number)getAttributeInternal(CODIGO);
    }

    /**Sets <code>value</code> as the attribute value for Codigo
     */
    public void setCodigo(Number value) {
        setAttributeInternal(CODIGO, value);
    }

    /**Gets the attribute value for CodigoAntigo, using the alias name CodigoAntigo
     */
    public String getCodigoAntigo() {
        return (String)getAttributeInternal(CODIGOANTIGO);
    }

    /**Sets <code>value</code> as the attribute value for CodigoAntigo
     */
    public void setCodigoAntigo(String value) {
        setAttributeInternal(CODIGOANTIGO, value);
    }

    /**Gets the attribute value for CodAux01, using the alias name CodAux01
     */
    public String getCodAux01() {
        return (String)getAttributeInternal(CODAUX01);
    }

    /**Sets <code>value</code> as the attribute value for CodAux01
     */
    public void setCodAux01(String value) {
        setAttributeInternal(CODAUX01, value);
    }

    /**Gets the attribute value for CodAux02, using the alias name CodAux02
     */
    public String getCodAux02() {
        return (String)getAttributeInternal(CODAUX02);
    }

    /**Sets <code>value</code> as the attribute value for CodAux02
     */
    public void setCodAux02(String value) {
        setAttributeInternal(CODAUX02, value);
    }

    /**Gets the attribute value for CodAux03, using the alias name CodAux03
     */
    public String getCodAux03() {
        return (String)getAttributeInternal(CODAUX03);
    }

    /**Sets <code>value</code> as the attribute value for CodAux03
     */
    public void setCodAux03(String value) {
        setAttributeInternal(CODAUX03, value);
    }

    /**Gets the attribute value for CodAux04, using the alias name CodAux04
     */
    public String getCodAux04() {
        return (String)getAttributeInternal(CODAUX04);
    }

    /**Sets <code>value</code> as the attribute value for CodAux04
     */
    public void setCodAux04(String value) {
        setAttributeInternal(CODAUX04, value);
    }

    /**Gets the attribute value for CodAux05, using the alias name CodAux05
     */
    public String getCodAux05() {
        return (String)getAttributeInternal(CODAUX05);
    }

    /**Sets <code>value</code> as the attribute value for CodAux05
     */
    public void setCodAux05(String value) {
        setAttributeInternal(CODAUX05, value);
    }

    /**Gets the attribute value for DataActivo, using the alias name DataActivo
     */
    public Date getDataActivo() {
        return (Date)getAttributeInternal(DATAACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for DataActivo
     */
    public void setDataActivo(Date value) {
        setAttributeInternal(DATAACTIVO, value);
    }

    /**Gets the attribute value for DataInactivo, using the alias name DataInactivo
     */
    public Date getDataInactivo() {
        return (Date)getAttributeInternal(DATAINACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for DataInactivo
     */
    public void setDataInactivo(Date value) {
        setAttributeInternal(DATAINACTIVO, value);
    }

    /**Gets the attribute value for DescAbrv, using the alias name DescAbrv
     */
    public String getDescAbrv() {
        return (String)getAttributeInternal(DESCABRV);
    }

    /**Sets <code>value</code> as the attribute value for DescAbrv
     */
    public void setDescAbrv(String value) {
        setAttributeInternal(DESCABRV, value);
    }

    /**Gets the attribute value for Designacao, using the alias name Designacao
     */
    public String getDesignacao() {
        return (String)getAttributeInternal(DESIGNACAO);
    }

    /**Sets <code>value</code> as the attribute value for Designacao
     */
    public void setDesignacao(String value) {
        setAttributeInternal(DESIGNACAO, value);
    }

    /**Gets the attribute value for Morada, using the alias name Morada
     */
    public String getMorada() {
        return (String)getAttributeInternal(MORADA);
    }

    /**Sets <code>value</code> as the attribute value for Morada
     */
    public void setMorada(String value) {
        setAttributeInternal(MORADA, value);
    }

    /**Gets the attribute value for PathImagem, using the alias name PathImagem
     */
    public String getPathImagem() {
        return (String)getAttributeInternal(PATHIMAGEM);
    }

    /**Sets <code>value</code> as the attribute value for PathImagem
     */
    public void setPathImagem(String value) {
        setAttributeInternal(PATHIMAGEM, value);
    }

    /**Gets the attribute value for SysEntidadesId, using the alias name SysEntidadesId
     */
    public Number getSysEntidadesId() {
        return (Number)getAttributeInternal(SYSENTIDADESID);
    }

    /**Sets <code>value</code> as the attribute value for SysEntidadesId
     */
    public void setSysEntidadesId(Number value) {
        setAttributeInternal(SYSENTIDADESID, value);
    }

    /**Gets the attribute value for SysSubtipoEntidadesId, using the alias name SysSubtipoEntidadesId
     */
    public Number getSysSubtipoEntidadesId() {
        return (Number)getAttributeInternal(SYSSUBTIPOENTIDADESID);
    }

    /**Sets <code>value</code> as the attribute value for SysSubtipoEntidadesId
     */
    public void setSysSubtipoEntidadesId(Number value) {
        setAttributeInternal(SYSSUBTIPOENTIDADESID, value);
    }

    /**Gets the attribute value for SysTiposCodigosId, using the alias name SysTiposCodigosId
     */
    public Number getSysTiposCodigosId() {
        return (Number)getAttributeInternal(SYSTIPOSCODIGOSID);
    }

    /**Sets <code>value</code> as the attribute value for SysTiposCodigosId
     */
    public void setSysTiposCodigosId(Number value) {
        setAttributeInternal(SYSTIPOSCODIGOSID, value);
    }

    /**Gets the attribute value for Telefone, using the alias name Telefone
     */
    public String getTelefone() {
        return (String)getAttributeInternal(TELEFONE);
    }

    /**Sets <code>value</code> as the attribute value for Telefone
     */
    public void setTelefone(String value) {
        setAttributeInternal(TELEFONE, value);
    }

    /**Gets the attribute value for Url, using the alias name Url
     */
    public String getUrl() {
        return (String)getAttributeInternal(URL);
    }

    /**Sets <code>value</code> as the attribute value for Url
     */
    public void setUrl(String value) {
        setAttributeInternal(URL, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case ACTIVO:
            return getActivo();
        case CODIGO:
            return getCodigo();
        case CODIGOANTIGO:
            return getCodigoAntigo();
        case CODAUX01:
            return getCodAux01();
        case CODAUX02:
            return getCodAux02();
        case CODAUX03:
            return getCodAux03();
        case CODAUX04:
            return getCodAux04();
        case CODAUX05:
            return getCodAux05();
        case DATAACTIVO:
            return getDataActivo();
        case DATAINACTIVO:
            return getDataInactivo();
        case DESCABRV:
            return getDescAbrv();
        case DESIGNACAO:
            return getDesignacao();
        case MORADA:
            return getMorada();
        case PATHIMAGEM:
            return getPathImagem();
        case SYSENTIDADESID:
            return getSysEntidadesId();
        case SYSSUBTIPOENTIDADESID:
            return getSysSubtipoEntidadesId();
        case SYSTIPOSCODIGOSID:
            return getSysTiposCodigosId();
        case TELEFONE:
            return getTelefone();
        case URL:
            return getUrl();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case SYSCODHIERID:
            return getSysCodHierId();
        case SYSCODIGOPOSTALID:
            return getSysCodigoPostalId();
        case ENTIDADE:
            return getEntidade();
        case CODIGOGENERICO:
            return getCodigoGenerico();
        case FERIADO:
            return getFeriado();
        case TIPOCODIGO:
            return getTipoCodigo();
        case SYSENTIDADESIDENTIDADE:
            return getSysEntidadesIdEntidade();
        case CODIGOHIERARQUICO:
            return getCodigoHierarquico();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((DBSequence)value);
            return;
        case ACTIVO:
            setActivo((String)value);
            return;
        case CODIGO:
            setCodigo((Number)value);
            return;
        case CODIGOANTIGO:
            setCodigoAntigo((String)value);
            return;
        case CODAUX01:
            setCodAux01((String)value);
            return;
        case CODAUX02:
            setCodAux02((String)value);
            return;
        case CODAUX03:
            setCodAux03((String)value);
            return;
        case CODAUX04:
            setCodAux04((String)value);
            return;
        case CODAUX05:
            setCodAux05((String)value);
            return;
        case DATAINACTIVO:
            setDataInactivo((Date)value);
            return;
        case DESCABRV:
            setDescAbrv((String)value);
            return;
        case DESIGNACAO:
            setDesignacao((String)value);
            return;
        case MORADA:
            setMorada((String)value);
            return;
        case PATHIMAGEM:
            setPathImagem((String)value);
            return;
        case SYSENTIDADESID:
            setSysEntidadesId((Number)value);
            return;
        case SYSSUBTIPOENTIDADESID:
            setSysSubtipoEntidadesId((Number)value);
            return;
        case SYSTIPOSCODIGOSID:
            setSysTiposCodigosId((Number)value);
            return;
        case TELEFONE:
            setTelefone((String)value);
            return;
        case URL:
            setUrl((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case SYSCODHIERID:
            setSysCodHierId((Number)value);
            return;
        case SYSCODIGOPOSTALID:
            setSysCodigoPostalId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity CodigoGenericoImpl
     */
    public RowIterator getCodigoGenerico() {
        return (RowIterator)getAttributeInternal(CODIGOGENERICO);
    }

    /**Sets <code>value</code> as the associated entity CodigoGenericoImpl
     */
    public void setCodigoGenerico(CodigoGenericoImpl value) {
        setAttributeInternal(CODIGOGENERICO, value);
    }

    /**Gets the attribute value for SysCodHierId, using the alias name SysCodHierId
     */
    public Number getSysCodHierId() {
        return (Number)getAttributeInternal(SYSCODHIERID);
    }

    /**Sets <code>value</code> as the attribute value for SysCodHierId
     */
    public void setSysCodHierId(Number value) {
        setAttributeInternal(SYSCODHIERID, value);
    }

    /**Gets the attribute value for SysCodigoPostalId, using the alias name SysCodigoPostalId
     */
    public Number getSysCodigoPostalId() {
        return (Number)getAttributeInternal(SYSCODIGOPOSTALID);
    }

    /**Sets <code>value</code> as the attribute value for SysCodigoPostalId
     */
    public void setSysCodigoPostalId(Number value) {
        setAttributeInternal(SYSCODIGOPOSTALID, value);
    }

    /**Gets the associated entity EntidadeImpl
     */
    public EntidadeImpl getSysEntidadesIdEntidade() {
        return (EntidadeImpl)getAttributeInternal(SYSENTIDADESIDENTIDADE);
    }

    /**Sets <code>value</code> as the associated entity EntidadeImpl
     */
    public void setSysEntidadesIdEntidade(EntidadeImpl value) {
        setAttributeInternal(SYSENTIDADESIDENTIDADE, value);
    }

    /**Gets the associated entity TipoCodigoImpl
     */
    public TipoCodigoImpl getTipoCodigo() {
        return (TipoCodigoImpl)getAttributeInternal(TIPOCODIGO);
    }

    /**Sets <code>value</code> as the associated entity TipoCodigoImpl
     */
    public void setTipoCodigo(TipoCodigoImpl value) {
        setAttributeInternal(TIPOCODIGO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public FeriadoImpl getFeriado() {
        return (FeriadoImpl)getAttributeInternal(FERIADO);
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getEntidade() {
        return (RowIterator)getAttributeInternal(ENTIDADE);
    }

    /**Sets <code>value</code> as the associated entity FeriadoImpl
     */
    public void setFeriado(FeriadoImpl value) {
        setAttributeInternal(FERIADO, value);
    }

    /**Gets the associated entity CodigoHierarquicoImpl
     */
    public CodigoHierarquicoImpl getCodigoHierarquico() {
        return (CodigoHierarquicoImpl)getAttributeInternal(CODIGOHIERARQUICO);
    }

    /**Sets <code>value</code> as the associated entity CodigoHierarquicoImpl
     */
    public void setCodigoHierarquico(CodigoHierarquicoImpl value) {
        setAttributeInternal(CODIGOHIERARQUICO, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }
}
