package ora.pt.cons.igif.sics.suporte;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FuncionalidadesModulosImpl extends EntityImpl {
    public static final int ID = 0;
    public static final int SYSOPCOESMENUID = 1;
    public static final int CODIGO = 2;
    public static final int DESCRICAO = 3;
    public static final int CREATEDBY = 4;
    public static final int CREATIONDATE = 5;
    public static final int LASTUPDATEDBY = 6;
    public static final int LASTUPDATEDATE = 7;
    public static final int OPCOESMENU = 8;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public FuncionalidadesModulosImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("ora.pt.cons.igif.sics.suporte.FuncionalidadesModulos");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for SysOpcoesMenuId, using the alias name SysOpcoesMenuId
     */
    public Number getSysOpcoesMenuId() {
        return (Number)getAttributeInternal(SYSOPCOESMENUID);
    }

    /**Sets <code>value</code> as the attribute value for SysOpcoesMenuId
     */
    public void setSysOpcoesMenuId(Number value) {
        setAttributeInternal(SYSOPCOESMENUID, value);
    }

    /**Gets the attribute value for Codigo, using the alias name Codigo
     */
    public String getCodigo() {
        return (String)getAttributeInternal(CODIGO);
    }

    /**Sets <code>value</code> as the attribute value for Codigo
     */
    public void setCodigo(String value) {
        setAttributeInternal(CODIGO, value);
    }

    /**Gets the attribute value for Descricao, using the alias name Descricao
     */
    public String getDescricao() {
        return (String)getAttributeInternal(DESCRICAO);
    }

    /**Sets <code>value</code> as the attribute value for Descricao
     */
    public void setDescricao(String value) {
        setAttributeInternal(DESCRICAO, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case SYSOPCOESMENUID:
            return getSysOpcoesMenuId();
        case CODIGO:
            return getCodigo();
        case DESCRICAO:
            return getDescricao();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case OPCOESMENU:
            return getOpcoesMenu();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((DBSequence)value);
            return;
        case SYSOPCOESMENUID:
            setSysOpcoesMenuId((Number)value);
            return;
        case CODIGO:
            setCodigo((String)value);
            return;
        case DESCRICAO:
            setDescricao((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity OpcoesMenuImpl
     */
    public OpcoesMenuImpl getOpcoesMenu() {
        return (OpcoesMenuImpl)getAttributeInternal(OPCOESMENU);
    }

    /**Sets <code>value</code> as the associated entity OpcoesMenuImpl
     */
    public void setOpcoesMenu(OpcoesMenuImpl value) {
        setAttributeInternal(OPCOESMENU, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }
}
