package ora.pt.cons.igif.sics.utentes;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HistFamiliaImpl extends EntityImpl {
    public static final int ID = 0;
    public static final int IDUFAMILIAID = 1;
    public static final int IDUINSCRID = 2;
    public static final int SCGPARENTESCOID = 3;
    public static final int NOP = 4;
    public static final int DATAINI = 5;
    public static final int DATAFIM = 6;
    public static final int CREATEDBY = 7;
    public static final int LASTUPDATEDBY = 8;
    public static final int CREATIONDATE = 9;
    public static final int LASTUPDATEDATE = 10;
    public static final int FAMILIA = 11;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public HistFamiliaImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("ora.pt.cons.igif.sics.utentes.HistFamilia");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for IduFamiliaId, using the alias name IduFamiliaId
     */
    public Number getIduFamiliaId() {
        return (Number)getAttributeInternal(IDUFAMILIAID);
    }

    /**Sets <code>value</code> as the attribute value for IduFamiliaId
     */
    public void setIduFamiliaId(Number value) {
        setAttributeInternal(IDUFAMILIAID, value);
    }

    /**Gets the attribute value for IduInscrId, using the alias name IduInscrId
     */
    public Number getIduInscrId() {
        return (Number)getAttributeInternal(IDUINSCRID);
    }

    /**Sets <code>value</code> as the attribute value for IduInscrId
     */
    public void setIduInscrId(Number value) {
        setAttributeInternal(IDUINSCRID, value);
    }

    /**Gets the attribute value for ScgParentescoId, using the alias name ScgParentescoId
     */
    public Number getScgParentescoId() {
        return (Number)getAttributeInternal(SCGPARENTESCOID);
    }

    /**Sets <code>value</code> as the attribute value for ScgParentescoId
     */
    public void setScgParentescoId(Number value) {
        setAttributeInternal(SCGPARENTESCOID, value);
    }

    /**Gets the attribute value for Nop, using the alias name Nop
     */
    public Number getNop() {
        return (Number)getAttributeInternal(NOP);
    }

    /**Sets <code>value</code> as the attribute value for Nop
     */
    public void setNop(Number value) {
        setAttributeInternal(NOP, value);
    }

    /**Gets the attribute value for DataIni, using the alias name DataIni
     */
    public Date getDataIni() {
        return (Date)getAttributeInternal(DATAINI);
    }

    /**Sets <code>value</code> as the attribute value for DataIni
     */
    public void setDataIni(Date value) {
        setAttributeInternal(DATAINI, value);
    }

    /**Gets the attribute value for DataFim, using the alias name DataFim
     */
    public Date getDataFim() {
        return (Date)getAttributeInternal(DATAFIM);
    }

    /**Sets <code>value</code> as the attribute value for DataFim
     */
    public void setDataFim(Date value) {
        setAttributeInternal(DATAFIM, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case IDUFAMILIAID:
            return getIduFamiliaId();
        case IDUINSCRID:
            return getIduInscrId();
        case SCGPARENTESCOID:
            return getScgParentescoId();
        case NOP:
            return getNop();
        case DATAINI:
            return getDataIni();
        case DATAFIM:
            return getDataFim();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case FAMILIA:
            return getFamilia();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((DBSequence)value);
            return;
        case IDUFAMILIAID:
            setIduFamiliaId((Number)value);
            return;
        case IDUINSCRID:
            setIduInscrId((Number)value);
            return;
        case SCGPARENTESCOID:
            setScgParentescoId((Number)value);
            return;
        case NOP:
            setNop((Number)value);
            return;
        case DATAINI:
            setDataIni((Date)value);
            return;
        case DATAFIM:
            setDataFim((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the associated entity FamiliaImpl
     */
    public FamiliaImpl getFamilia() {
        return (FamiliaImpl)getAttributeInternal(FAMILIA);
    }

    /**Sets <code>value</code> as the associated entity FamiliaImpl
     */
    public void setFamilia(FamiliaImpl value) {
        setAttributeInternal(FAMILIA, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }
}
