package ora.pt.cons.igif.sics.utentes.client;

import ora.pt.cons.igif.sics.utentes.common.IdentificacoesUtente;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IdentificacoesUtenteClient extends ViewUsageImpl implements IdentificacoesUtente {
    /**This is the default constructor (do not remove)
     */
    public IdentificacoesUtenteClient() {
    }

    public boolean isValidNiss(String niss) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"isValidNiss",new String [] {"java.lang.String"},new Object[] {niss});
        return ((Boolean)_ret).booleanValue();
    }
}
