package ora.pt.cons.igif.sics;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InformacaoUtilizadorRowImpl extends ViewRowImpl {
    public static final int CSID = 0;
    public static final int NMECANOG1 = 6;
    public static final int CSDESC = 1;
    public static final int PROFISSIDPESSOALID = 2;
    public static final int NOMECLIN = 3;
    public static final int CODCS = 4;
    public static final int NOME = 5;
    public static final int PAPEL = 6;
    public static final int PERFILID = 7;
    public static final int PROFID = 8;
    public static final int USERID = 9;
    public static final int USERNAME = 10;
    public static final int CODIGOCS = 11;
    public static final int DESCRICAOTIPOCS = 12;

    /**This is the default constructor (do not remove)
     */
    public InformacaoUtilizadorRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute CsId
     */
    public Number getCsId() {
        return (Number) getAttributeInternal(CSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CsId
     */
    public void setCsId(Number value) {
        setAttributeInternal(CSID, value);
    }

    /**Gets the attribute value for the calculated attribute CsDesc
     */
    public String getCsDesc() {
        return (String) getAttributeInternal(CSDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CsDesc
     */
    public void setCsDesc(String value) {
        setAttributeInternal(CSDESC, value);
    }

    /**Gets the attribute value for the calculated attribute ProfId
     */
    public Number getProfId() {
        return (Number) getAttributeInternal(PROFID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProfId
     */
    public void setProfId(Number value) {
        setAttributeInternal(PROFID, value);
    }

    /**Gets the attribute value for the calculated attribute Nomeclin
     */
    public String getNomeclin() {
        return (String) getAttributeInternal(NOMECLIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomeclin
     */
    public void setNomeclin(String value) {
        setAttributeInternal(NOMECLIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CSID:
            return getCsId();
        case CSDESC:
            return getCsDesc();
        case PROFISSIDPESSOALID:
            return getProfissidPessoalId();
        case NOMECLIN:
            return getNomeclin();
        case CODCS:
            return getCodCs();
        case NOME:
            return getnome();
        case PAPEL:
            return getpapel();
        case PERFILID:
            return getPerfilId();
        case PROFID:
            return getProfId();
        case USERID:
            return getUserId();
        case USERNAME:
            return getUsername();
        case CODIGOCS:
            return getCodigoCs();
        case DESCRICAOTIPOCS:
            return getDescricaotipoCs();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CSID:
            setCsId((Number)value);
            return;
        case CSDESC:
            setCsDesc((String)value);
            return;
        case PROFISSIDPESSOALID:
            setProfissidPessoalId((Number)value);
            return;
        case NOMECLIN:
            setNomeclin((String)value);
            return;
        case CODCS:
            setCodCs((Number)value);
            return;
        case PERFILID:
            setPerfilId((Number)value);
            return;
        case PROFID:
            setProfId((Number)value);
            return;
        case USERID:
            setUserId((Number)value);
            return;
        case USERNAME:
            setUsername((String)value);
            return;
        case CODIGOCS:
            setCodigoCs((String)value);
            return;
        case DESCRICAOTIPOCS:
            setDescricaotipoCs((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute CodCs
     */
    public Number getCodCs() {
        return (Number) getAttributeInternal(CODCS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodCs
     */
    public void setCodCs(Number value) {
        setAttributeInternal(CODCS, value);
    }

    /**Gets the attribute value for the calculated attribute nome
     */
    public String getnome() {
        return (String) getAttributeInternal(NOME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute nome
     */
    public void setnome(String value) {
        setAttributeInternal(NOME, value);
    }


    /**Gets the attribute value for the calculated attribute papel
     */
    public String getpapel() {
        return (String) getAttributeInternal(PAPEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute papel
     */
    public void setpapel(String value) {
        setAttributeInternal(PAPEL, value);
    }


    /**Gets the attribute value for the calculated attribute PerfilId
     */
    public Number getPerfilId() {
        return (Number) getAttributeInternal(PERFILID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PerfilId
     */
    public void setPerfilId(Number value) {
        setAttributeInternal(PERFILID, value);
    }


    /**Gets the attribute value for the calculated attribute nmecanog1
     */
    public String getnmecanog1() {
        return (String) getAttributeInternal(NMECANOG1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute nmecanog1
     */
    public void setnmecanog1(String value) {
        setAttributeInternal(NMECANOG1, value);
    }
     
    /**Gets the attribute value for the calculated attribute UserId
     */
    public Number getUserId() {
        return (Number) getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }    


    /**Gets the attribute value for the calculated attribute ProfissidPessoalId
     */
    public Number getProfissidPessoalId() {
        return (Number) getAttributeInternal(PROFISSIDPESSOALID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProfissidPessoalId
     */
    public void setProfissidPessoalId(Number value) {
        setAttributeInternal(PROFISSIDPESSOALID, value);
    }


    /**Gets the attribute value for the calculated attribute Username
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Username
     */
    public void setUsername(String value) {
        setAttributeInternal(USERNAME, value);
    }


    /**Gets the attribute value for the calculated attribute CodigoCs
     */
    public String getCodigoCs() {
        return (String) getAttributeInternal(CODIGOCS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodigoCs
     */
    public void setCodigoCs(String value) {
        setAttributeInternal(CODIGOCS, value);
    }


    /**Gets the attribute value for the calculated attribute DescricaotipoCs
     */
    public String getDescricaotipoCs() {
        return (String) getAttributeInternal(DESCRICAOTIPOCS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DescricaotipoCs
     */
    public void setDescricaotipoCs(String value) {
        setAttributeInternal(DESCRICAOTIPOCS, value);
    }


}
