package ora.pt.cons.igif.sics.baixas;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemBaixaViewRowImpl extends ViewRowImpl {
    public static final int ANULADO = 0;
    public static final int AUTORIZSAIDA = 1;
    public static final int COMUNICACAOANULACAOCRSS = 2;
    public static final int COMUNICACAOCRSS = 3;
    public static final int CREATEDBY = 4;
    public static final int CREATIONDATE = 5;
    public static final int CUIDADOSINADIAVEIS = 6;
    public static final int DATAANULADO = 7;
    public static final int DATAINICIO = 8;
    public static final int DATATERMO = 9;
    public static final int GITBAIXASID = 10;
    public static final int ID = 11;
    public static final int IDPAI = 12;
    public static final int INCAPACITADO = 13;
    public static final int INTERNAMENTO = 14;
    public static final int JUSTIFICACAOSAIDA = 15;
    public static final int LASTUPDATEDBY = 16;
    public static final int LASTUPDATEDATE = 17;
    public static final int SCGCLASSIFDOENCAID = 18;
    public static final int SCGTIPOALTAID = 19;
    public static final int SCGTIPOREGISTOID = 20;
    public static final int SYSENTIDADESID = 21;
    public static final int SCGMOTIVOANULACAOID = 22;
    public static final int SYSENTIDADESANULUCAOID = 23;
    public static final int COMENTARIOANULACAO = 24;
    public static final int PROPROFISSIDPESSOALID = 25;
    public static final int PROPROFISSIDPESANULACAOID = 26;
    public static final int CIRURGIAAMBULATORIO = 27;
    public static final int NUMEPISODIO = 28;
    public static final int SCGCODMODULOID = 29;

    /**This is the default constructor (do not remove)
     */
    public ItemBaixaViewRowImpl() {
    }

    /**Gets ItemBaixa entity object.
     */
    public ItemBaixaImpl getItemBaixa() {
        return (ItemBaixaImpl)getEntity(0);
    }

    /**Gets the attribute value for ANULADO using the alias name Anulado
     */
    public String getAnulado() {
        return (String) getAttributeInternal(ANULADO);
    }

    /**Sets <code>value</code> as attribute value for ANULADO using the alias name Anulado
     */
    public void setAnulado(String value) {
        setAttributeInternal(ANULADO, value);
    }

    /**Gets the attribute value for AUTORIZ_SAIDA using the alias name AutorizSaida
     */
    public String getAutorizSaida() {
        return (String) getAttributeInternal(AUTORIZSAIDA);
    }

    /**Sets <code>value</code> as attribute value for AUTORIZ_SAIDA using the alias name AutorizSaida
     */
    public void setAutorizSaida(String value) {
        setAttributeInternal(AUTORIZSAIDA, value);
    }

    /**Gets the attribute value for COMUNICACAO_ANULACAO_CRSS using the alias name ComunicacaoAnulacaoCrss
     */
    public String getComunicacaoAnulacaoCrss() {
        return (String) getAttributeInternal(COMUNICACAOANULACAOCRSS);
    }

    /**Sets <code>value</code> as attribute value for COMUNICACAO_ANULACAO_CRSS using the alias name ComunicacaoAnulacaoCrss
     */
    public void setComunicacaoAnulacaoCrss(String value) {
        setAttributeInternal(COMUNICACAOANULACAOCRSS, value);
    }

    /**Gets the attribute value for COMUNICACAO_CRSS using the alias name ComunicacaoCrss
     */
    public String getComunicacaoCrss() {
        return (String) getAttributeInternal(COMUNICACAOCRSS);
    }

    /**Sets <code>value</code> as attribute value for COMUNICACAO_CRSS using the alias name ComunicacaoCrss
     */
    public void setComunicacaoCrss(String value) {
        setAttributeInternal(COMUNICACAOCRSS, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CUIDADOS_INADIAVEIS using the alias name CuidadosInadiaveis
     */
    public String getCuidadosInadiaveis() {
        return (String) getAttributeInternal(CUIDADOSINADIAVEIS);
    }

    /**Sets <code>value</code> as attribute value for CUIDADOS_INADIAVEIS using the alias name CuidadosInadiaveis
     */
    public void setCuidadosInadiaveis(String value) {
        setAttributeInternal(CUIDADOSINADIAVEIS, value);
    }

    /**Gets the attribute value for DATA_ANULADO using the alias name DataAnulado
     */
    public Date getDataAnulado() {
        return (Date) getAttributeInternal(DATAANULADO);
    }

    /**Sets <code>value</code> as attribute value for DATA_ANULADO using the alias name DataAnulado
     */
    public void setDataAnulado(Date value) {
        setAttributeInternal(DATAANULADO, value);
    }

    /**Gets the attribute value for DATA_INICIO using the alias name DataInicio
     */
    public Date getDataInicio() {
        return (Date) getAttributeInternal(DATAINICIO);
    }

    /**Sets <code>value</code> as attribute value for DATA_INICIO using the alias name DataInicio
     */
    public void setDataInicio(Date value) {
        setAttributeInternal(DATAINICIO, value);
    }

    /**Gets the attribute value for DATA_TERMO using the alias name DataTermo
     */
    public Date getDataTermo() {
        return (Date) getAttributeInternal(DATATERMO);
    }

    /**Sets <code>value</code> as attribute value for DATA_TERMO using the alias name DataTermo
     */
    public void setDataTermo(Date value) {
        setAttributeInternal(DATATERMO, value);
    }

    /**Gets the attribute value for GIT_BAIXAS_ID using the alias name GitBaixasId
     */
    public Number getGitBaixasId() {
        return (Number) getAttributeInternal(GITBAIXASID);
    }

    /**Sets <code>value</code> as attribute value for GIT_BAIXAS_ID using the alias name GitBaixasId
     */
    public void setGitBaixasId(Number value) {
        setAttributeInternal(GITBAIXASID, value);
    }

    /**Gets the attribute value for ID using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for ID_PAI using the alias name IdPai
     */
    public Number getIdPai() {
        return (Number) getAttributeInternal(IDPAI);
    }

    /**Sets <code>value</code> as attribute value for ID_PAI using the alias name IdPai
     */
    public void setIdPai(Number value) {
        setAttributeInternal(IDPAI, value);
    }

    /**Gets the attribute value for INCAPACITADO using the alias name Incapacitado
     */
    public String getIncapacitado() {
        return (String) getAttributeInternal(INCAPACITADO);
    }

    /**Sets <code>value</code> as attribute value for INCAPACITADO using the alias name Incapacitado
     */
    public void setIncapacitado(String value) {
        setAttributeInternal(INCAPACITADO, value);
    }

    /**Gets the attribute value for INTERNAMENTO using the alias name Internamento
     */
    public String getInternamento() {
        return (String) getAttributeInternal(INTERNAMENTO);
    }

    /**Sets <code>value</code> as attribute value for INTERNAMENTO using the alias name Internamento
     */
    public void setInternamento(String value) {
        setAttributeInternal(INTERNAMENTO, value);
    }

    /**Gets the attribute value for JUSTIFICACAO_SAIDA using the alias name JustificacaoSaida
     */
    public String getJustificacaoSaida() {
        return (String) getAttributeInternal(JUSTIFICACAOSAIDA);
    }

    /**Sets <code>value</code> as attribute value for JUSTIFICACAO_SAIDA using the alias name JustificacaoSaida
     */
    public void setJustificacaoSaida(String value) {
        setAttributeInternal(JUSTIFICACAOSAIDA, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }


    /**Gets the attribute value for SCG_CLASSIFDOENCA_ID using the alias name ScgClassifdoencaId
     */
    public Number getScgClassifdoencaId() {
        return (Number) getAttributeInternal(SCGCLASSIFDOENCAID);
    }

    /**Sets <code>value</code> as attribute value for SCG_CLASSIFDOENCA_ID using the alias name ScgClassifdoencaId
     */
    public void setScgClassifdoencaId(Number value) {
        setAttributeInternal(SCGCLASSIFDOENCAID, value);
    }


    /**Gets the attribute value for SCG_TIPOALTA_ID using the alias name ScgTipoaltaId
     */
    public Number getScgTipoaltaId() {
        return (Number) getAttributeInternal(SCGTIPOALTAID);
    }

    /**Sets <code>value</code> as attribute value for SCG_TIPOALTA_ID using the alias name ScgTipoaltaId
     */
    public void setScgTipoaltaId(Number value) {
        setAttributeInternal(SCGTIPOALTAID, value);
    }

    /**Gets the attribute value for SCG_TIPOREGISTO_ID using the alias name ScgTiporegistoId
     */
    public Number getScgTiporegistoId() {
        return (Number) getAttributeInternal(SCGTIPOREGISTOID);
    }

    /**Sets <code>value</code> as attribute value for SCG_TIPOREGISTO_ID using the alias name ScgTiporegistoId
     */
    public void setScgTiporegistoId(Number value) {
        setAttributeInternal(SCGTIPOREGISTOID, value);
    }

    /**Gets the attribute value for SYS_ENTIDADES_ID using the alias name SysEntidadesId
     */
    public Number getSysEntidadesId() {
        return (Number) getAttributeInternal(SYSENTIDADESID);
    }

    /**Sets <code>value</code> as attribute value for SYS_ENTIDADES_ID using the alias name SysEntidadesId
     */
    public void setSysEntidadesId(Number value) {
        setAttributeInternal(SYSENTIDADESID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ANULADO:
            return getAnulado();
        case AUTORIZSAIDA:
            return getAutorizSaida();
        case COMUNICACAOANULACAOCRSS:
            return getComunicacaoAnulacaoCrss();
        case COMUNICACAOCRSS:
            return getComunicacaoCrss();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CUIDADOSINADIAVEIS:
            return getCuidadosInadiaveis();
        case DATAANULADO:
            return getDataAnulado();
        case DATAINICIO:
            return getDataInicio();
        case DATATERMO:
            return getDataTermo();
        case GITBAIXASID:
            return getGitBaixasId();
        case ID:
            return getId();
        case IDPAI:
            return getIdPai();
        case INCAPACITADO:
            return getIncapacitado();
        case INTERNAMENTO:
            return getInternamento();
        case JUSTIFICACAOSAIDA:
            return getJustificacaoSaida();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case SCGCLASSIFDOENCAID:
            return getScgClassifdoencaId();
        case SCGTIPOALTAID:
            return getScgTipoaltaId();
        case SCGTIPOREGISTOID:
            return getScgTiporegistoId();
        case SYSENTIDADESID:
            return getSysEntidadesId();
        case SCGMOTIVOANULACAOID:
            return getScgMotivoAnulacaoId();
        case SYSENTIDADESANULUCAOID:
            return getSysEntidadesAnulucaoId();
        case COMENTARIOANULACAO:
            return getComentarioAnulacao();
        case PROPROFISSIDPESSOALID:
            return getProProfissidPessoalId();
        case PROPROFISSIDPESANULACAOID:
            return getProProfissidPesAnulacaoId();
        case CIRURGIAAMBULATORIO:
            return getCirurgiaAmbulatorio();
        case NUMEPISODIO:
            return getNumEpisodio();
        case SCGCODMODULOID:
            return getScgCodModuloId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ANULADO:
            setAnulado((String)value);
            return;
        case AUTORIZSAIDA:
            setAutorizSaida((String)value);
            return;
        case COMUNICACAOANULACAOCRSS:
            setComunicacaoAnulacaoCrss((String)value);
            return;
        case COMUNICACAOCRSS:
            setComunicacaoCrss((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CUIDADOSINADIAVEIS:
            setCuidadosInadiaveis((String)value);
            return;
        case DATAANULADO:
            setDataAnulado((Date)value);
            return;
        case DATAINICIO:
            setDataInicio((Date)value);
            return;
        case DATATERMO:
            setDataTermo((Date)value);
            return;
        case GITBAIXASID:
            setGitBaixasId((Number)value);
            return;
        case ID:
            setId((DBSequence)value);
            return;
        case IDPAI:
            setIdPai((Number)value);
            return;
        case INCAPACITADO:
            setIncapacitado((String)value);
            return;
        case INTERNAMENTO:
            setInternamento((String)value);
            return;
        case JUSTIFICACAOSAIDA:
            setJustificacaoSaida((String)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case SCGCLASSIFDOENCAID:
            setScgClassifdoencaId((Number)value);
            return;
        case SCGTIPOALTAID:
            setScgTipoaltaId((Number)value);
            return;
        case SCGTIPOREGISTOID:
            setScgTiporegistoId((Number)value);
            return;
        case SYSENTIDADESID:
            setSysEntidadesId((Number)value);
            return;
        case SCGMOTIVOANULACAOID:
            setScgMotivoAnulacaoId((Number)value);
            return;
        case SYSENTIDADESANULUCAOID:
            setSysEntidadesAnulucaoId((Number)value);
            return;
        case COMENTARIOANULACAO:
            setComentarioAnulacao((String)value);
            return;
        case PROPROFISSIDPESSOALID:
            setProProfissidPessoalId((Number)value);
            return;
        case PROPROFISSIDPESANULACAOID:
            setProProfissidPesAnulacaoId((Number)value);
            return;
        case CIRURGIAAMBULATORIO:
            setCirurgiaAmbulatorio((String)value);
            return;
        case NUMEPISODIO:
            setNumEpisodio((Number)value);
            return;
        case SCGCODMODULOID:
            setScgCodModuloId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for SCG_MOTIVO_ANULACAO_ID using the alias name ScgMotivoAnulacaoId
     */
    public Number getScgMotivoAnulacaoId() {
        return (Number) getAttributeInternal(SCGMOTIVOANULACAOID);
    }

    /**Sets <code>value</code> as attribute value for SCG_MOTIVO_ANULACAO_ID using the alias name ScgMotivoAnulacaoId
     */
    public void setScgMotivoAnulacaoId(Number value) {
        setAttributeInternal(SCGMOTIVOANULACAOID, value);
    }


    /**Gets the attribute value for SYS_ENTIDADES_ANULUCAO_ID using the alias name SysEntidadesAnulucaoId
     */
    public Number getSysEntidadesAnulucaoId() {
        return (Number) getAttributeInternal(SYSENTIDADESANULUCAOID);
    }

    /**Sets <code>value</code> as attribute value for SYS_ENTIDADES_ANULUCAO_ID using the alias name SysEntidadesAnulucaoId
     */
    public void setSysEntidadesAnulucaoId(Number value) {
        setAttributeInternal(SYSENTIDADESANULUCAOID, value);
    }

    /**Gets the attribute value for COMENTARIO_ANULACAO using the alias name ComentarioAnulacao
     */
    public String getComentarioAnulacao() {
        return (String) getAttributeInternal(COMENTARIOANULACAO);
    }

    /**Sets <code>value</code> as attribute value for COMENTARIO_ANULACAO using the alias name ComentarioAnulacao
     */
    public void setComentarioAnulacao(String value) {
        setAttributeInternal(COMENTARIOANULACAO, value);
    }

    /**Gets the attribute value for PRO_PROFISSID_PESSOAL_ID using the alias name ProProfissidPessoalId
     */
    public Number getProProfissidPessoalId() {
        return (Number) getAttributeInternal(PROPROFISSIDPESSOALID);
    }

    /**Sets <code>value</code> as attribute value for PRO_PROFISSID_PESSOAL_ID using the alias name ProProfissidPessoalId
     */
    public void setProProfissidPessoalId(Number value) {
        setAttributeInternal(PROPROFISSIDPESSOALID, value);
    }

    /**Gets the attribute value for PRO_PROFISSID_PES_ANULACAO_ID using the alias name ProProfissidPesAnulacaoId
     */
    public Number getProProfissidPesAnulacaoId() {
        return (Number) getAttributeInternal(PROPROFISSIDPESANULACAOID);
    }

    /**Sets <code>value</code> as attribute value for PRO_PROFISSID_PES_ANULACAO_ID using the alias name ProProfissidPesAnulacaoId
     */
    public void setProProfissidPesAnulacaoId(Number value) {
        setAttributeInternal(PROPROFISSIDPESANULACAOID, value);
    }

    /**Gets the attribute value for CIRURGIA_AMBULATORIO using the alias name CirurgiaAmbulatorio
     */
    public String getCirurgiaAmbulatorio() {
        return (String) getAttributeInternal(CIRURGIAAMBULATORIO);
    }

    /**Sets <code>value</code> as attribute value for CIRURGIA_AMBULATORIO using the alias name CirurgiaAmbulatorio
     */
    public void setCirurgiaAmbulatorio(String value) {
        setAttributeInternal(CIRURGIAAMBULATORIO, value);
    }

    /**Gets the attribute value for NUM_EPISODIO using the alias name NumEpisodio
     */
    public Number getNumEpisodio() {
        return (Number) getAttributeInternal(NUMEPISODIO);
    }

    /**Sets <code>value</code> as attribute value for NUM_EPISODIO using the alias name NumEpisodio
     */
    public void setNumEpisodio(Number value) {
        setAttributeInternal(NUMEPISODIO, value);
    }

    /**Gets the attribute value for SCG_COD_MODULO_ID using the alias name ScgCodModuloId
     */
    public Number getScgCodModuloId() {
        return (Number) getAttributeInternal(SCGCODMODULOID);
    }

    /**Sets <code>value</code> as attribute value for SCG_COD_MODULO_ID using the alias name ScgCodModuloId
     */
    public void setScgCodModuloId(Number value) {
        setAttributeInternal(SCGCODMODULOID, value);
    }
}
