package ora.pt.cons.igif.sics.utentes.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class ListaAgregadoFamiliarRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "NomeCompleto_LABEL", "Nome" },
{ "IhfDataFim_FMT_FORMAT", "dd-MM-yyyy" },
{ "IduInscrId_LABEL", "IduInscrId" },
{ "Nutente_LABEL", "Nº Utente" },
{ "CodParentesco_LABEL", "CodParentesco" },
{ "NomeEquipa_LABEL", "Médico" },
{ "IhfDataFim_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DtaNasc_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataFim_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DtaNasc_LABEL", "Data Nasc." },
{ "DataFim_FMT_FORMAT", "dd-MM-yyyy" },
{ "DescParentesco_LABEL", "Grau" },
{ "IduFamiliaId_LABEL", "IduFamiliaId" },
{ "DtaNasc_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" }};

    /**This is the default constructor (do not remove)
     */
    public ListaAgregadoFamiliarRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
