package ora.pt.cons.igif.sics.baixas.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class ListaItemsBaixasRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "Datatermo_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "Datacriacao_LABEL", "Data Criação" },
{ "Dtanascfamiliar_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "Datainicio_FMT_FORMAT", "dd-MM-yyyy" },
{ "Datatermo__FMT_FORMAT", "dd-MM-yyyy" },
{ "Classdoenca_LABEL", "Classificação" },
{ "Cirurgiaambulatorio_LABEL", "B" },
{ "Datainicio_LABEL", "Dt. Início" },
{ "Autorizsaida_LABEL", "A" },
{ "Cuidadosinadiaveis_LABEL", "C" },
{ "Datatermo_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataAnulado_FMT_FORMAT", "dd-MM-yyyy" },
{ "Datatermo_LABEL", "Dt. Termo" },
{ "Datacriacao_FMT_FORMAT", "dd-MM-yyyy HH:mm" },
{ "Datainicio_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "Internamento_LABEL", "T" },
{ "Datatermo__FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "Dtanascfamiliar_FMT_FORMAT", "dd-MM-yyyy" },
{ "Incapacitado_LABEL", "I" },
{ "Tiporegisto_LABEL", "Tipo Registo" },
{ "Datacriacao_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataAnulado_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" }};

    /**This is the default constructor (do not remove)
     */
    public ListaItemsBaixasRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
