package ora.pt.cons.igif.sics.suporte;

import ora.pt.cons.igif.sics.suporte.common.ListaCodigosGenericosRow;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaCodigosGenericosRowImpl extends ViewRowImpl implements ListaCodigosGenericosRow {
    public static final int ID = 0;
    public static final int ACTIVO = 1;
    public static final int CODIGO = 2;
    public static final int CODIGOANTIGO = 3;
    public static final int DATAACTIVO = 4;
    public static final int DATAINACTIVO = 5;
    public static final int DESCRICAO = 6;
    public static final int DESCABRV = 7;
    public static final int LIMITEMAX = 8;
    public static final int LIMITEMIN = 9;
    public static final int OBSERVACOES = 10;
    public static final int ORDENACAO = 11;
    public static final int SCGSYSENTIDADESID = 12;
    public static final int SYSTIPOSCODIGOSID = 13;
    public static final int TIPOCODIGOCODTIPO = 14;
    public static final int TIPOCODDESCR = 15;
    public static final int TIPOCODCENTRAL = 16;
    public static final int CODIGOTABELA = 17;

    /**This is the default constructor (do not remove)
     */
    public ListaCodigosGenericosRowImpl() {
    }


    /**Gets the attribute value for ID using the alias name Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for ACTIVO using the alias name Activo
     */
    public String getActivo() {
        return (String) getAttributeInternal(ACTIVO);
    }

    /**Sets <code>value</code> as attribute value for ACTIVO using the alias name Activo
     */
    public void setActivo(String value) {
        setAttributeInternal(ACTIVO, value);
    }

    /**Gets the attribute value for CODIGO using the alias name Codigo
     */
    public String getCodigo() {
        return (String) getAttributeInternal(CODIGO);
    }

    /**Sets <code>value</code> as attribute value for CODIGO using the alias name Codigo
     */
    public void setCodigo(String value) {
        setAttributeInternal(CODIGO, value);
    }

    /**Gets the attribute value for CODIGO_ANTIGO using the alias name CodigoAntigo
     */
    public String getCodigoAntigo() {
        return (String) getAttributeInternal(CODIGOANTIGO);
    }

    /**Sets <code>value</code> as attribute value for CODIGO_ANTIGO using the alias name CodigoAntigo
     */
    public void setCodigoAntigo(String value) {
        setAttributeInternal(CODIGOANTIGO, value);
    }

    /**Gets the attribute value for DATA_ACTIVO using the alias name DataActivo
     */
    public Date getDataActivo() {
        return (Date) getAttributeInternal(DATAACTIVO);
    }

    /**Sets <code>value</code> as attribute value for DATA_ACTIVO using the alias name DataActivo
     */
    public void setDataActivo(Date value) {
        setAttributeInternal(DATAACTIVO, value);
    }

    /**Gets the attribute value for DATA_INACTIVO using the alias name DataInactivo
     */
    public Date getDataInactivo() {
        return (Date) getAttributeInternal(DATAINACTIVO);
    }

    /**Sets <code>value</code> as attribute value for DATA_INACTIVO using the alias name DataInactivo
     */
    public void setDataInactivo(Date value) {
        setAttributeInternal(DATAINACTIVO, value);
    }

    /**Gets the attribute value for DESCRICAO using the alias name Descricao
     */
    public String getDescricao() {
        return (String) getAttributeInternal(DESCRICAO);
    }

    /**Sets <code>value</code> as attribute value for DESCRICAO using the alias name Descricao
     */
    public void setDescricao(String value) {
        setAttributeInternal(DESCRICAO, value);
    }

    /**Gets the attribute value for DESC_ABRV using the alias name DescAbrv
     */
    public String getDescAbrv() {
        return (String) getAttributeInternal(DESCABRV);
    }

    /**Sets <code>value</code> as attribute value for DESC_ABRV using the alias name DescAbrv
     */
    public void setDescAbrv(String value) {
        setAttributeInternal(DESCABRV, value);
    }

    /**Gets the attribute value for LIMITE_MAX using the alias name LimiteMax
     */
    public Number getLimiteMax() {
        return (Number) getAttributeInternal(LIMITEMAX);
    }

    /**Sets <code>value</code> as attribute value for LIMITE_MAX using the alias name LimiteMax
     */
    public void setLimiteMax(Number value) {
        setAttributeInternal(LIMITEMAX, value);
    }

    /**Gets the attribute value for LIMITE_MIN using the alias name LimiteMin
     */
    public Number getLimiteMin() {
        return (Number) getAttributeInternal(LIMITEMIN);
    }

    /**Sets <code>value</code> as attribute value for LIMITE_MIN using the alias name LimiteMin
     */
    public void setLimiteMin(Number value) {
        setAttributeInternal(LIMITEMIN, value);
    }

    /**Gets the attribute value for OBSERVACOES using the alias name Observacoes
     */
    public String getObservacoes() {
        return (String) getAttributeInternal(OBSERVACOES);
    }

    /**Sets <code>value</code> as attribute value for OBSERVACOES using the alias name Observacoes
     */
    public void setObservacoes(String value) {
        setAttributeInternal(OBSERVACOES, value);
    }

    /**Gets the attribute value for ORDENACAO using the alias name Ordenacao
     */
    public Number getOrdenacao() {
        return (Number) getAttributeInternal(ORDENACAO);
    }

    /**Sets <code>value</code> as attribute value for ORDENACAO using the alias name Ordenacao
     */
    public void setOrdenacao(Number value) {
        setAttributeInternal(ORDENACAO, value);
    }


    /**Gets the attribute value for SYS_TIPOS_CODIGOS_ID using the alias name SysTiposCodigosId
     */
    public Number getSysTiposCodigosId() {
        return (Number) getAttributeInternal(SYSTIPOSCODIGOSID);
    }

    /**Sets <code>value</code> as attribute value for SYS_TIPOS_CODIGOS_ID using the alias name SysTiposCodigosId
     */
    public void setSysTiposCodigosId(Number value) {
        setAttributeInternal(SYSTIPOSCODIGOSID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case ACTIVO:
            return getActivo();
        case CODIGO:
            return getCodigo();
        case CODIGOANTIGO:
            return getCodigoAntigo();
        case DATAACTIVO:
            return getDataActivo();
        case DATAINACTIVO:
            return getDataInactivo();
        case DESCRICAO:
            return getDescricao();
        case DESCABRV:
            return getDescAbrv();
        case LIMITEMAX:
            return getLimiteMax();
        case LIMITEMIN:
            return getLimiteMin();
        case OBSERVACOES:
            return getObservacoes();
        case ORDENACAO:
            return getOrdenacao();
        case SCGSYSENTIDADESID:
            return getScgSysEntidadesId();
        case SYSTIPOSCODIGOSID:
            return getSysTiposCodigosId();
        case TIPOCODIGOCODTIPO:
            return getTipocodigoCodtipo();
        case TIPOCODDESCR:
            return getTipocodDescr();
        case TIPOCODCENTRAL:
            return getTipocodCentral();
        case CODIGOTABELA:
            return getCodigoTabela();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case ACTIVO:
            setActivo((String)value);
            return;
        case CODIGO:
            setCodigo((String)value);
            return;
        case CODIGOANTIGO:
            setCodigoAntigo((String)value);
            return;
        case DATAACTIVO:
            setDataActivo((Date)value);
            return;
        case DATAINACTIVO:
            setDataInactivo((Date)value);
            return;
        case DESCRICAO:
            setDescricao((String)value);
            return;
        case DESCABRV:
            setDescAbrv((String)value);
            return;
        case LIMITEMAX:
            setLimiteMax((Number)value);
            return;
        case LIMITEMIN:
            setLimiteMin((Number)value);
            return;
        case OBSERVACOES:
            setObservacoes((String)value);
            return;
        case ORDENACAO:
            setOrdenacao((Number)value);
            return;
        case SCGSYSENTIDADESID:
            setScgSysEntidadesId((Number)value);
            return;
        case SYSTIPOSCODIGOSID:
            setSysTiposCodigosId((Number)value);
            return;
        case TIPOCODIGOCODTIPO:
            setTipocodigoCodtipo((String)value);
            return;
        case TIPOCODDESCR:
            setTipocodDescr((String)value);
            return;
        case TIPOCODCENTRAL:
            setTipocodCentral((String)value);
            return;
        case CODIGOTABELA:
            setCodigoTabela((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute TipocodigoCodTipo
     */
    public String getTipocodigoCodTipo() {
        return (String) getAttributeInternal(TIPOCODIGOCODTIPO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TipocodigoCodTipo
     */
    public void setTipocodigoCodTipo(String value) {
        setAttributeInternal(TIPOCODIGOCODTIPO, value);
    }


    /**Gets the attribute value for the calculated attribute ScgSysEntidadesId
     */
    public Number getScgSysEntidadesId() {
        return (Number) getAttributeInternal(SCGSYSENTIDADESID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ScgSysEntidadesId
     */
    public void setScgSysEntidadesId(Number value) {
        setAttributeInternal(SCGSYSENTIDADESID, value);
    }

    /**Gets the attribute value for the calculated attribute TipocodigoCodtipo
     */
    public String getTipocodigoCodtipo() {
        return (String) getAttributeInternal(TIPOCODIGOCODTIPO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TipocodigoCodtipo
     */
    public void setTipocodigoCodtipo(String value) {
        setAttributeInternal(TIPOCODIGOCODTIPO, value);
    }


    /**Gets the attribute value for the calculated attribute TipocodDescr
     */
    public String getTipocodDescr() {
        return (String) getAttributeInternal(TIPOCODDESCR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TipocodDescr
     */
    public void setTipocodDescr(String value) {
        setAttributeInternal(TIPOCODDESCR, value);
    }

    /**Gets the attribute value for the calculated attribute TipocodCentral
     */
    public String getTipocodCentral() {
        return (String) getAttributeInternal(TIPOCODCENTRAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TipocodCentral
     */
    public void setTipocodCentral(String value) {
        setAttributeInternal(TIPOCODCENTRAL, value);
    }

    /**Gets the attribute value for the calculated attribute CodigoTabela
     */
    public String getCodigoTabela() {
        return (String) getAttributeInternal(CODIGOTABELA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodigoTabela
     */
    public void setCodigoTabela(String value) {
        setAttributeInternal(CODIGOTABELA, value);
    }
}
