package ora.pt.cons.igif.sics.suporte.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ListaEntidadesResponsaveisRow extends Row {
    String getCartao();

    String getCodigo();

    String getDescrAbvr();

    String getDesignacao();

    String getEntDefault();

    Number getId();

    Number getIduIdentUtId();

    String getNumbenef();

    void setCartao(String value);

    void setCodigo(String value);

    void setDescrAbvr(String value);

    void setDesignacao(String value);

    void setEntDefault(String value);

    void setId(Number value);

    void setIduIdentUtId(Number value);

    void setNumbenef(String value);
}
