package ora.pt.cons.igif.sics.suporte.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaEntidadesResponsaveisRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public ListaEntidadesResponsaveisRowClient() {
    }


    public String getCartao() {
        return (String)getAttribute("Cartao");
    }

    public String getCodigo() {
        return (String)getAttribute("Codigo");
    }

    public String getDescrAbvr() {
        return (String)getAttribute("DescrAbvr");
    }

    public String getDesignacao() {
        return (String)getAttribute("Designacao");
    }

    public String getEntDefault() {
        return (String)getAttribute("EntDefault");
    }

    public Number getId() {
        return (Number)getAttribute("Id");
    }

    public Number getIduIdentUtId() {
        return (Number)getAttribute("IduIdentUtId");
    }

    public String getNumbenef() {
        return (String)getAttribute("Numbenef");
    }

    public void setCartao(String value) {
        setAttribute("Cartao", value);
    }

    public void setCodigo(String value) {
        setAttribute("Codigo", value);
    }

    public void setDescrAbvr(String value) {
        setAttribute("DescrAbvr", value);
    }

    public void setDesignacao(String value) {
        setAttribute("Designacao", value);
    }

    public void setEntDefault(String value) {
        setAttribute("EntDefault", value);
    }

    public void setId(Number value) {
        setAttribute("Id", value);
    }

    public void setIduIdentUtId(Number value) {
        setAttribute("IduIdentUtId", value);
    }

    public void setNumbenef(String value) {
        setAttribute("Numbenef", value);
    }
}
