package ora.pt.cons.igif.sics.suporte.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class ListaCodigosGenericosRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "DataInactivo_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataInactivo_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataActivo_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataActivo_FMT_FORMAT", "dd-MM-yyyy" }};

    /**This is the default constructor (do not remove)
     */
    public ListaCodigosGenericosRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
