package ora.pt.cons.igif.sics.baixas.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class ListaBaixasRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "Dataalta_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataInicioTotal_FMT_FORMAT", "dd-MM-yyyy" },
{ "Dtanascfamiliar_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataInicio_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataInicio_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataInicioTotal_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataInicio_LABEL", "Data" },
{ "Profissional_LABEL", "Médico" },
{ "DataTermo_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "Dataalta_FMT_FORMAT", "dd-MM-yyyy" },
{ "Entidade_LABEL", "Centro de Saúde" },
{ "Dtanascfamiliar_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataTermo_FMT_FORMAT", "dd-MM-yyyy" }};

    /**This is the default constructor (do not remove)
     */
    public ListaBaixasRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
