package ora.pt.cons.igif.sics.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ListaParametros extends ViewObject {

    void setPathForUrlsRedirect();

    void setPathForUrlsRedirectBaixa();

    String getPath();

    void setPath(String value);

    void setPathForUrlsRedirectPesquisaUtente();

    void setPathForUrlsRedirectReceitas();

    void setPathForUrlsFromContext(String context);


    long getEstimatedRowCount();

    void setPathForReportServerUrl();

    void setPathForReportsMedParam();
     
    void setPathForReportsGitParam();

    void setPathForUrlsRedirectAdminSinc();    

    void setPathForReportsIdentificacaoParam();
}
