package ora.pt.cons.igif.sics.baixas;

import ora.pt.cons.igif.sics.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OperacoesLogViewImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public OperacoesLogViewImpl() {
    }
}
