// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.1.0, build 061008.0900.00025)

package ora.pt.cons.igif.services.proxy.renovacao;

public interface SaudeCCRenovacaoRespostaIdentificarCidadaoType extends java.rmi.Remote {
    public void saudeCCRenovacaoRespostaIdentificarCidadao(javax.xml.soap.SOAPElement saudeCCRenovacaoRespostaIdentificarCidadaoParameters) throws 
         java.rmi.RemoteException;
}
