// This source file is generated by Oracle tools and is subject to change
// It is a utility client for invoking the operations of the Web service port.
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.1.0, build 061008.0900.00025)

package ora.pt.cons.igif.services.proxy.identificacao;

import oracle.webservices.transport.ClientTransport;
import oracle.webservices.OracleStub;
import javax.xml.rpc.ServiceFactory;
import javax.xml.rpc.Stub;

public class SaudeCCRespostaIdentificarCidadaoPortClient {
    private ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoType _port;
    
    public SaudeCCRespostaIdentificarCidadaoPortClient() throws Exception {
        ServiceFactory factory = ServiceFactory.newInstance();
        _port = ((ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoService)factory.loadService(ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoService.class)).getSaudeCCRespostaIdentificarCidadaoPort();
    }
    
    /**
     * @param args
     */
    public static void main(String[] args) {
        try {
            ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoPortClient myPort = new ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoPortClient();
            System.out.println("calling " + myPort.getEndpoint());
            // Add your own code here
        
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * delegate all operations to the underlying implementation class.
     */
    
    public void saudeCCRespostaIdentificarCidadao(javax.xml.soap.SOAPElement saudeCCRespostaIdentificarCidadaoParameters) throws java.rmi.RemoteException {
        _port.saudeCCRespostaIdentificarCidadao(saudeCCRespostaIdentificarCidadaoParameters);
    }
    
    
    /**
     * used to access the JAX-RPC level APIs
     * returns the interface of the port instance
     */
    public ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoType getPort() {
        return _port;
    }
    
    public String getEndpoint() {
        return (String) ((Stub) _port)._getProperty(Stub.ENDPOINT_ADDRESS_PROPERTY);
    }
    
    public void setEndpoint(String endpoint) {
        ((Stub) _port)._setProperty(Stub.ENDPOINT_ADDRESS_PROPERTY, endpoint);
    }
    
    public String getPassword() {
        return (String) ((Stub) _port)._getProperty(Stub.PASSWORD_PROPERTY);
    }
    
    public void setPassword(String password) {
        ((Stub) _port)._setProperty(Stub.PASSWORD_PROPERTY, password);
    }
    
    public String getUsername() {
        return (String) ((Stub) _port)._getProperty(Stub.USERNAME_PROPERTY);
    }
    
    public void setUsername(String username) {
        ((Stub) _port)._setProperty(Stub.USERNAME_PROPERTY, username);
    }
    
    public void setMaintainSession(boolean maintainSession) {
        ((Stub) _port)._setProperty(Stub.SESSION_MAINTAIN_PROPERTY, Boolean.valueOf(maintainSession));
    }
    
    public boolean getMaintainSession() {
        return ((Boolean) ((Stub) _port)._getProperty(Stub.SESSION_MAINTAIN_PROPERTY)).booleanValue();
    }
    
    /**
     * returns the transport context
     */
    public ClientTransport getClientTransport() {
        return ((OracleStub) _port).getClientTransport();
    }
    
}
