package ora.pt.cons.igif.sics.utentes;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetalheUtenteRowImpl extends ViewRowImpl {
    public static final int IDIID = 0;
    public static final int NIR = 1;
    public static final int NISS = 2;
    public static final int NOMECOMPLETO = 3;
    public static final int DATANASC = 4;
    public static final int SEXO = 5;
    public static final int NACIONALIDADE = 6;
    public static final int TIPOBI = 7;
    public static final int NDOCIDENT = 8;
    public static final int NIF = 9;
    public static final int ENTRESP = 10;
    public static final int NUMBENEF = 11;
    public static final int DATAVALCART = 12;
    public static final int CPAISNAT = 13;
    public static final int DISTRITONAT = 14;
    public static final int CONCELHONAT = 15;
    public static final int FREGUESIANAT = 16;
    public static final int MORADAVIA = 17;
    public static final int MORADARUA = 18;
    public static final int MORADAEDIFICIO = 19;
    public static final int MORADAPORTA = 20;
    public static final int MORADALUGAR = 21;
    public static final int MORADALOCAL = 22;
    public static final int MORADADISTRITO = 23;
    public static final int MORADACONCELHO = 24;
    public static final int MORADAFREGUESIA = 25;
    public static final int CODPOSTAL1 = 26;
    public static final int CODPOSTAL2 = 27;
    public static final int CODPOSTALLOCAL = 28;
    public static final int EMAIL = 29;
    public static final int TELF = 30;
    public static final int DATAINSCR = 31;
    public static final int DESCTPINSCR = 32;
    public static final int NUMMEDICO = 33;
    public static final int NOMEMEDICO = 34;
    public static final int CENTROSAUDE = 35;
    public static final int BENEFRECMDESCR = 36;
    public static final int BENEFRECMDTAINI = 37;
    public static final int BENEFRECMDTAFIM = 38;
    public static final int BENEFISENCAODESCR = 39;
    public static final int BENEFISENCAODTAINI = 40;
    public static final int BENEFISENCAODTAFIM = 41;

    /**This is the default constructor (do not remove)
     */
    public DetalheUtenteRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute IdiId
     */
    public Number getIdiId() {
        return (Number) getAttributeInternal(IDIID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdiId
     */
    public void setIdiId(Number value) {
        setAttributeInternal(IDIID, value);
    }

    /**Gets the attribute value for the calculated attribute Nir
     */
    public Number getNir() {
        return (Number) getAttributeInternal(NIR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nir
     */
    public void setNir(Number value) {
        setAttributeInternal(NIR, value);
    }

    /**Gets the attribute value for the calculated attribute Niss
     */
    public Number getNiss() {
        return (Number) getAttributeInternal(NISS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Niss
     */
    public void setNiss(Number value) {
        setAttributeInternal(NISS, value);
    }

    /**Gets the attribute value for the calculated attribute NomeCompleto
     */
    public String getNomeCompleto() {
        return (String) getAttributeInternal(NOMECOMPLETO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NomeCompleto
     */
    public void setNomeCompleto(String value) {
        setAttributeInternal(NOMECOMPLETO, value);
    }

    /**Gets the attribute value for the calculated attribute DataNasc
     */
    public Date getDataNasc() {
        return (Date) getAttributeInternal(DATANASC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataNasc
     */
    public void setDataNasc(Date value) {
        setAttributeInternal(DATANASC, value);
    }

    /**Gets the attribute value for the calculated attribute Sexo
     */
    public String getSexo() {
        return (String) getAttributeInternal(SEXO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sexo
     */
    public void setSexo(String value) {
        setAttributeInternal(SEXO, value);
    }

    /**Gets the attribute value for the calculated attribute Nacionalidade
     */
    public String getNacionalidade() {
        return (String) getAttributeInternal(NACIONALIDADE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nacionalidade
     */
    public void setNacionalidade(String value) {
        setAttributeInternal(NACIONALIDADE, value);
    }

    /**Gets the attribute value for the calculated attribute TipoBi
     */
    public String getTipoBi() {
        return (String) getAttributeInternal(TIPOBI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TipoBi
     */
    public void setTipoBi(String value) {
        setAttributeInternal(TIPOBI, value);
    }

    /**Gets the attribute value for the calculated attribute NDocIdent
     */
    public String getNDocIdent() {
        return (String) getAttributeInternal(NDOCIDENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NDocIdent
     */
    public void setNDocIdent(String value) {
        setAttributeInternal(NDOCIDENT, value);
    }

    /**Gets the attribute value for the calculated attribute Nif
     */
    public Number getNif() {
        return (Number) getAttributeInternal(NIF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nif
     */
    public void setNif(Number value) {
        setAttributeInternal(NIF, value);
    }

    /**Gets the attribute value for the calculated attribute EntResp
     */
    public String getEntResp() {
        return (String) getAttributeInternal(ENTRESP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EntResp
     */
    public void setEntResp(String value) {
        setAttributeInternal(ENTRESP, value);
    }

    /**Gets the attribute value for the calculated attribute NumBenef
     */
    public String getNumBenef() {
        return (String) getAttributeInternal(NUMBENEF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumBenef
     */
    public void setNumBenef(String value) {
        setAttributeInternal(NUMBENEF, value);
    }

    /**Gets the attribute value for the calculated attribute DataValCart
     */
    public Date getDataValCart() {
        return (Date) getAttributeInternal(DATAVALCART);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataValCart
     */
    public void setDataValCart(Date value) {
        setAttributeInternal(DATAVALCART, value);
    }

    /**Gets the attribute value for the calculated attribute CPaisNat
     */
    public String getCPaisNat() {
        return (String) getAttributeInternal(CPAISNAT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CPaisNat
     */
    public void setCPaisNat(String value) {
        setAttributeInternal(CPAISNAT, value);
    }

    /**Gets the attribute value for the calculated attribute DistritoNat
     */
    public String getDistritoNat() {
        return (String) getAttributeInternal(DISTRITONAT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DistritoNat
     */
    public void setDistritoNat(String value) {
        setAttributeInternal(DISTRITONAT, value);
    }

    /**Gets the attribute value for the calculated attribute ConcelhoNat
     */
    public String getConcelhoNat() {
        return (String) getAttributeInternal(CONCELHONAT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConcelhoNat
     */
    public void setConcelhoNat(String value) {
        setAttributeInternal(CONCELHONAT, value);
    }

    /**Gets the attribute value for the calculated attribute FreguesiaNat
     */
    public String getFreguesiaNat() {
        return (String) getAttributeInternal(FREGUESIANAT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FreguesiaNat
     */
    public void setFreguesiaNat(String value) {
        setAttributeInternal(FREGUESIANAT, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaVia
     */
    public String getMoradaVia() {
        return (String) getAttributeInternal(MORADAVIA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaVia
     */
    public void setMoradaVia(String value) {
        setAttributeInternal(MORADAVIA, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaRua
     */
    public String getMoradaRua() {
        return (String) getAttributeInternal(MORADARUA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaRua
     */
    public void setMoradaRua(String value) {
        setAttributeInternal(MORADARUA, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaEdificio
     */
    public String getMoradaEdificio() {
        return (String) getAttributeInternal(MORADAEDIFICIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaEdificio
     */
    public void setMoradaEdificio(String value) {
        setAttributeInternal(MORADAEDIFICIO, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaPorta
     */
    public String getMoradaPorta() {
        return (String) getAttributeInternal(MORADAPORTA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaPorta
     */
    public void setMoradaPorta(String value) {
        setAttributeInternal(MORADAPORTA, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaLugar
     */
    public String getMoradaLugar() {
        return (String) getAttributeInternal(MORADALUGAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaLugar
     */
    public void setMoradaLugar(String value) {
        setAttributeInternal(MORADALUGAR, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaLocal
     */
    public String getMoradaLocal() {
        return (String) getAttributeInternal(MORADALOCAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaLocal
     */
    public void setMoradaLocal(String value) {
        setAttributeInternal(MORADALOCAL, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaDistrito
     */
    public String getMoradaDistrito() {
        return (String) getAttributeInternal(MORADADISTRITO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaDistrito
     */
    public void setMoradaDistrito(String value) {
        setAttributeInternal(MORADADISTRITO, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaConcelho
     */
    public String getMoradaConcelho() {
        return (String) getAttributeInternal(MORADACONCELHO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaConcelho
     */
    public void setMoradaConcelho(String value) {
        setAttributeInternal(MORADACONCELHO, value);
    }

    /**Gets the attribute value for the calculated attribute MoradaFreguesia
     */
    public String getMoradaFreguesia() {
        return (String) getAttributeInternal(MORADAFREGUESIA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MoradaFreguesia
     */
    public void setMoradaFreguesia(String value) {
        setAttributeInternal(MORADAFREGUESIA, value);
    }

    /**Gets the attribute value for the calculated attribute CodPostal1
     */
    public Number getCodPostal1() {
        return (Number) getAttributeInternal(CODPOSTAL1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodPostal1
     */
    public void setCodPostal1(Number value) {
        setAttributeInternal(CODPOSTAL1, value);
    }

    /**Gets the attribute value for the calculated attribute CodPostal2
     */
    public Number getCodPostal2() {
        return (Number) getAttributeInternal(CODPOSTAL2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodPostal2
     */
    public void setCodPostal2(Number value) {
        setAttributeInternal(CODPOSTAL2, value);
    }

    /**Gets the attribute value for the calculated attribute CodPostalLocal
     */
    public String getCodPostalLocal() {
        return (String) getAttributeInternal(CODPOSTALLOCAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodPostalLocal
     */
    public void setCodPostalLocal(String value) {
        setAttributeInternal(CODPOSTALLOCAL, value);
    }

    /**Gets the attribute value for the calculated attribute Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**Gets the attribute value for the calculated attribute Telf
     */
    public String getTelf() {
        return (String) getAttributeInternal(TELF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Telf
     */
    public void setTelf(String value) {
        setAttributeInternal(TELF, value);
    }

    /**Gets the attribute value for the calculated attribute DataInscr
     */
    public Date getDataInscr() {
        return (Date) getAttributeInternal(DATAINSCR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataInscr
     */
    public void setDataInscr(Date value) {
        setAttributeInternal(DATAINSCR, value);
    }

    /**Gets the attribute value for the calculated attribute DescTpInscr
     */
    public String getDescTpInscr() {
        return (String) getAttributeInternal(DESCTPINSCR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DescTpInscr
     */
    public void setDescTpInscr(String value) {
        setAttributeInternal(DESCTPINSCR, value);
    }

    /**Gets the attribute value for the calculated attribute NumMedico
     */
    public Number getNumMedico() {
        return (Number) getAttributeInternal(NUMMEDICO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumMedico
     */
    public void setNumMedico(Number value) {
        setAttributeInternal(NUMMEDICO, value);
    }

    /**Gets the attribute value for the calculated attribute NomeMedico
     */
    public String getNomeMedico() {
        return (String) getAttributeInternal(NOMEMEDICO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NomeMedico
     */
    public void setNomeMedico(String value) {
        setAttributeInternal(NOMEMEDICO, value);
    }

    /**Gets the attribute value for the calculated attribute CentroSaude
     */
    public String getCentroSaude() {
        return (String) getAttributeInternal(CENTROSAUDE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CentroSaude
     */
    public void setCentroSaude(String value) {
        setAttributeInternal(CENTROSAUDE, value);
    }

    /**Gets the attribute value for the calculated attribute BenefRecmDescr
     */
    public String getBenefRecmDescr() {
        return (String) getAttributeInternal(BENEFRECMDESCR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BenefRecmDescr
     */
    public void setBenefRecmDescr(String value) {
        setAttributeInternal(BENEFRECMDESCR, value);
    }

    /**Gets the attribute value for the calculated attribute BenefRecmDtaIni
     */
    public Date getBenefRecmDtaIni() {
        return (Date) getAttributeInternal(BENEFRECMDTAINI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BenefRecmDtaIni
     */
    public void setBenefRecmDtaIni(Date value) {
        setAttributeInternal(BENEFRECMDTAINI, value);
    }

    /**Gets the attribute value for the calculated attribute BenefRecmDtaFim
     */
    public Date getBenefRecmDtaFim() {
        return (Date) getAttributeInternal(BENEFRECMDTAFIM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BenefRecmDtaFim
     */
    public void setBenefRecmDtaFim(Date value) {
        setAttributeInternal(BENEFRECMDTAFIM, value);
    }

    /**Gets the attribute value for the calculated attribute BenefIsencaoDescr
     */
    public String getBenefIsencaoDescr() {
        return (String) getAttributeInternal(BENEFISENCAODESCR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BenefIsencaoDescr
     */
    public void setBenefIsencaoDescr(String value) {
        setAttributeInternal(BENEFISENCAODESCR, value);
    }

    /**Gets the attribute value for the calculated attribute BenefIsencaoDtaIni
     */
    public Date getBenefIsencaoDtaIni() {
        return (Date) getAttributeInternal(BENEFISENCAODTAINI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BenefIsencaoDtaIni
     */
    public void setBenefIsencaoDtaIni(Date value) {
        setAttributeInternal(BENEFISENCAODTAINI, value);
    }

    /**Gets the attribute value for the calculated attribute BenefIsencaoDtaFim
     */
    public Date getBenefIsencaoDtaFim() {
        return (Date) getAttributeInternal(BENEFISENCAODTAFIM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BenefIsencaoDtaFim
     */
    public void setBenefIsencaoDtaFim(Date value) {
        setAttributeInternal(BENEFISENCAODTAFIM, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDIID:
            return getIdiId();
        case NIR:
            return getNir();
        case NISS:
            return getNiss();
        case NOMECOMPLETO:
            return getNomeCompleto();
        case DATANASC:
            return getDataNasc();
        case SEXO:
            return getSexo();
        case NACIONALIDADE:
            return getNacionalidade();
        case TIPOBI:
            return getTipoBi();
        case NDOCIDENT:
            return getNDocIdent();
        case NIF:
            return getNif();
        case ENTRESP:
            return getEntResp();
        case NUMBENEF:
            return getNumBenef();
        case DATAVALCART:
            return getDataValCart();
        case CPAISNAT:
            return getCPaisNat();
        case DISTRITONAT:
            return getDistritoNat();
        case CONCELHONAT:
            return getConcelhoNat();
        case FREGUESIANAT:
            return getFreguesiaNat();
        case MORADAVIA:
            return getMoradaVia();
        case MORADARUA:
            return getMoradaRua();
        case MORADAEDIFICIO:
            return getMoradaEdificio();
        case MORADAPORTA:
            return getMoradaPorta();
        case MORADALUGAR:
            return getMoradaLugar();
        case MORADALOCAL:
            return getMoradaLocal();
        case MORADADISTRITO:
            return getMoradaDistrito();
        case MORADACONCELHO:
            return getMoradaConcelho();
        case MORADAFREGUESIA:
            return getMoradaFreguesia();
        case CODPOSTAL1:
            return getCodPostal1();
        case CODPOSTAL2:
            return getCodPostal2();
        case CODPOSTALLOCAL:
            return getCodPostalLocal();
        case EMAIL:
            return getEmail();
        case TELF:
            return getTelf();
        case DATAINSCR:
            return getDataInscr();
        case DESCTPINSCR:
            return getDescTpInscr();
        case NUMMEDICO:
            return getNumMedico();
        case NOMEMEDICO:
            return getNomeMedico();
        case CENTROSAUDE:
            return getCentroSaude();
        case BENEFRECMDESCR:
            return getBenefRecmDescr();
        case BENEFRECMDTAINI:
            return getBenefRecmDtaIni();
        case BENEFRECMDTAFIM:
            return getBenefRecmDtaFim();
        case BENEFISENCAODESCR:
            return getBenefIsencaoDescr();
        case BENEFISENCAODTAINI:
            return getBenefIsencaoDtaIni();
        case BENEFISENCAODTAFIM:
            return getBenefIsencaoDtaFim();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDIID:
            setIdiId((Number)value);
            return;
        case NIR:
            setNir((Number)value);
            return;
        case NISS:
            setNiss((Number)value);
            return;
        case NOMECOMPLETO:
            setNomeCompleto((String)value);
            return;
        case DATANASC:
            setDataNasc((Date)value);
            return;
        case SEXO:
            setSexo((String)value);
            return;
        case NACIONALIDADE:
            setNacionalidade((String)value);
            return;
        case TIPOBI:
            setTipoBi((String)value);
            return;
        case NDOCIDENT:
            setNDocIdent((String)value);
            return;
        case NIF:
            setNif((Number)value);
            return;
        case ENTRESP:
            setEntResp((String)value);
            return;
        case NUMBENEF:
            setNumBenef((String)value);
            return;
        case DATAVALCART:
            setDataValCart((Date)value);
            return;
        case CPAISNAT:
            setCPaisNat((String)value);
            return;
        case DISTRITONAT:
            setDistritoNat((String)value);
            return;
        case CONCELHONAT:
            setConcelhoNat((String)value);
            return;
        case FREGUESIANAT:
            setFreguesiaNat((String)value);
            return;
        case MORADAVIA:
            setMoradaVia((String)value);
            return;
        case MORADARUA:
            setMoradaRua((String)value);
            return;
        case MORADAEDIFICIO:
            setMoradaEdificio((String)value);
            return;
        case MORADAPORTA:
            setMoradaPorta((String)value);
            return;
        case MORADALUGAR:
            setMoradaLugar((String)value);
            return;
        case MORADALOCAL:
            setMoradaLocal((String)value);
            return;
        case MORADADISTRITO:
            setMoradaDistrito((String)value);
            return;
        case MORADACONCELHO:
            setMoradaConcelho((String)value);
            return;
        case MORADAFREGUESIA:
            setMoradaFreguesia((String)value);
            return;
        case CODPOSTAL1:
            setCodPostal1((Number)value);
            return;
        case CODPOSTAL2:
            setCodPostal2((Number)value);
            return;
        case CODPOSTALLOCAL:
            setCodPostalLocal((String)value);
            return;
        case EMAIL:
            setEmail((String)value);
            return;
        case TELF:
            setTelf((String)value);
            return;
        case DATAINSCR:
            setDataInscr((Date)value);
            return;
        case DESCTPINSCR:
            setDescTpInscr((String)value);
            return;
        case NUMMEDICO:
            setNumMedico((Number)value);
            return;
        case NOMEMEDICO:
            setNomeMedico((String)value);
            return;
        case CENTROSAUDE:
            setCentroSaude((String)value);
            return;
        case BENEFRECMDESCR:
            setBenefRecmDescr((String)value);
            return;
        case BENEFRECMDTAINI:
            setBenefRecmDtaIni((Date)value);
            return;
        case BENEFRECMDTAFIM:
            setBenefRecmDtaFim((Date)value);
            return;
        case BENEFISENCAODESCR:
            setBenefIsencaoDescr((String)value);
            return;
        case BENEFISENCAODTAINI:
            setBenefIsencaoDtaIni((Date)value);
            return;
        case BENEFISENCAODTAFIM:
            setBenefIsencaoDtaFim((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
