package ora.pt.cons.igif.sics.utentes;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntidadeUtenteImpl extends EntityImpl {
    public static final int CARTAO = 0;
    public static final int CREATEDBY = 1;
    public static final int CREATIONDATE = 2;
    public static final int DATAFIM = 3;
    public static final int DATAINI = 4;
    public static final int DTAVAL = 5;
    public static final int ENTDEFAULT = 6;
    public static final int ID = 7;
    public static final int IDUIDENTUTID = 8;
    public static final int LASTUPDATEDBY = 9;
    public static final int LASTUPDATEDATE = 10;
    public static final int NUMBENEF = 11;
    public static final int ROWID = 12;
    public static final int SYSENTIDADESRESPID = 13;
    public static final int IDENTIFICACAOUTENTE = 14;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public EntidadeUtenteImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("ora.pt.cons.igif.sics.utentes.EntidadeUtente");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Cartao, using the alias name Cartao
     */
    public String getCartao() {
        return (String)getAttributeInternal(CARTAO);
    }

    /**Sets <code>value</code> as the attribute value for Cartao
     */
    public void setCartao(String value) {
        setAttributeInternal(CARTAO, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for DataFim, using the alias name DataFim
     */
    public Date getDataFim() {
        return (Date)getAttributeInternal(DATAFIM);
    }

    /**Sets <code>value</code> as the attribute value for DataFim
     */
    public void setDataFim(Date value) {
        setAttributeInternal(DATAFIM, value);
    }

    /**Gets the attribute value for DataIni, using the alias name DataIni
     */
    public Date getDataIni() {
        return (Date)getAttributeInternal(DATAINI);
    }

    /**Sets <code>value</code> as the attribute value for DataIni
     */
    public void setDataIni(Date value) {
        setAttributeInternal(DATAINI, value);
    }

    /**Gets the attribute value for DtaVal, using the alias name DtaVal
     */
    public Date getDtaVal() {
        return (Date)getAttributeInternal(DTAVAL);
    }

    /**Sets <code>value</code> as the attribute value for DtaVal
     */
    public void setDtaVal(Date value) {
        setAttributeInternal(DTAVAL, value);
    }

    /**Gets the attribute value for EntDefault, using the alias name EntDefault
     */
    public String getEntDefault() {
        return (String)getAttributeInternal(ENTDEFAULT);
    }

    /**Sets <code>value</code> as the attribute value for EntDefault
     */
    public void setEntDefault(String value) {
        setAttributeInternal(ENTDEFAULT, value);
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for IduIdentUtId, using the alias name IduIdentUtId
     */
    public Number getIduIdentUtId() {
        return (Number)getAttributeInternal(IDUIDENTUTID);
    }

    /**Sets <code>value</code> as the attribute value for IduIdentUtId
     */
    public void setIduIdentUtId(Number value) {
        setAttributeInternal(IDUIDENTUTID, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for Numbenef, using the alias name Numbenef
     */
    public String getNumbenef() {
        return (String)getAttributeInternal(NUMBENEF);
    }

    /**Sets <code>value</code> as the attribute value for Numbenef
     */
    public void setNumbenef(String value) {
        setAttributeInternal(NUMBENEF, value);
    }

    /**Gets the attribute value for RowID, using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**Gets the attribute value for SysEntidadesRespId, using the alias name SysEntidadesRespId
     */
    public Number getSysEntidadesRespId() {
        return (Number)getAttributeInternal(SYSENTIDADESRESPID);
    }

    /**Sets <code>value</code> as the attribute value for SysEntidadesRespId
     */
    public void setSysEntidadesRespId(Number value) {
        setAttributeInternal(SYSENTIDADESRESPID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CARTAO:
            return getCartao();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case DATAFIM:
            return getDataFim();
        case DATAINI:
            return getDataIni();
        case DTAVAL:
            return getDtaVal();
        case ENTDEFAULT:
            return getEntDefault();
        case ID:
            return getId();
        case IDUIDENTUTID:
            return getIduIdentUtId();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case NUMBENEF:
            return getNumbenef();
        case ROWID:
            return getRowID();
        case SYSENTIDADESRESPID:
            return getSysEntidadesRespId();
        case IDENTIFICACAOUTENTE:
            return getIdentificacaoUtente();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CARTAO:
            setCartao((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case DATAFIM:
            setDataFim((Date)value);
            return;
        case DATAINI:
            setDataIni((Date)value);
            return;
        case DTAVAL:
            setDtaVal((Date)value);
            return;
        case ENTDEFAULT:
            setEntDefault((String)value);
            return;
        case ID:
            setId((DBSequence)value);
            return;
        case IDUIDENTUTID:
            setIduIdentUtId((Number)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case NUMBENEF:
            setNumbenef((String)value);
            return;
        case SYSENTIDADESRESPID:
            setSysEntidadesRespId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity IdentificacaoUtenteImpl
     */
    public IdentificacaoUtenteImpl getIdentificacaoUtente() {
        return (IdentificacaoUtenteImpl)getAttributeInternal(IDENTIFICACAOUTENTE);
    }

    /**Sets <code>value</code> as the associated entity IdentificacaoUtenteImpl
     */
    public void setIdentificacaoUtente(IdentificacaoUtenteImpl value) {
        setAttributeInternal(IDENTIFICACAOUTENTE, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }
}
