package ora.pt.cons.igif.sics.utentes;

import java.sql.CallableStatement;
import java.sql.SQLException;

import java.sql.Types;

import ora.pt.cons.igif.sics.baixas.ItemBaixaImpl;

import oracle.adf.model.generic.RowImpl;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IdentificacaoUtenteImpl extends EntityImpl {
    public static final int ID = 0;
    public static final int APELIDOS = 1;
    public static final int APELIDOSMAE = 2;
    public static final int APELIDOSPAI = 3;
    public static final int BI = 4;
    public static final int CIDADENAT = 5;
    public static final int DATAULTCONTACTO = 6;
    public static final int DTANASC = 7;
    public static final int LOCALIDADENAT = 8;
    public static final int NACIONAL = 9;
    public static final int NICS = 10;
    public static final int NIF = 11;
    public static final int NIR = 12;
    public static final int NISS = 13;
    public static final int NOMESPROPRIOS = 14;
    public static final int NOMESPROPRIOSMAE = 15;
    public static final int NOMESPROPRIOSPAI = 16;
    public static final int NOMECOMPLETO = 17;
    public static final int NUMVIAS = 18;
    public static final int REGIAONAT = 19;
    public static final int REGUMIC = 20;
    public static final int SCGPROFISSAOID = 21;
    public static final int SCGSITPROFID = 22;
    public static final int SCGTIPOBIID = 23;
    public static final int SCHCDAINENACID = 24;
    public static final int SCHCDAINENATID = 25;
    public static final int SCHPAISNATID = 26;
    public static final int SEXO = 27;
    public static final int CREATEDBY = 28;
    public static final int CREATIONDATE = 29;
    public static final int LASTUPDATEDBY = 30;
    public static final int LASTUPDATEDATE = 31;
    public static final int ACTIVO = 32;
    public static final int SCHCDAINENATANTID = 33;
    public static final int CHAVE1 = 34;
    public static final int CHAVE2 = 35;
    public static final int APLSOLTEIRO = 36;
    public static final int NOMEPESQUISA = 37;
    public static final int SINCDMLID = 38;
    public static final int SINCDATE = 39;
    public static final int SCGNHABILITID = 40;
    public static final int INSCRICAOUTENTE = 41;
    public static final int ENTIDADEUTENTE = 42;
    public static final int BENEFICIODOUTENTE = 43;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public IdentificacaoUtenteImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("ora.pt.cons.igif.sics.utentes.IdentificacaoUtente");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for Apelidos, using the alias name Apelidos
     */
    public String getApelidos() {
        return (String)getAttributeInternal(APELIDOS);
    }

    /**Sets <code>value</code> as the attribute value for Apelidos
     */
    public void setApelidos(String value) {
        setAttributeInternal(APELIDOS, value);
    }

    /**Gets the attribute value for ApelidosMae, using the alias name ApelidosMae
     */
    public String getApelidosMae() {
        return (String)getAttributeInternal(APELIDOSMAE);
    }

    /**Sets <code>value</code> as the attribute value for ApelidosMae
     */
    public void setApelidosMae(String value) {
        setAttributeInternal(APELIDOSMAE, value);
    }

    /**Gets the attribute value for ApelidosPai, using the alias name ApelidosPai
     */
    public String getApelidosPai() {
        return (String)getAttributeInternal(APELIDOSPAI);
    }

    /**Sets <code>value</code> as the attribute value for ApelidosPai
     */
    public void setApelidosPai(String value) {
        setAttributeInternal(APELIDOSPAI, value);
    }

    /**Gets the attribute value for Bi, using the alias name Bi
     */
    public String getBi() {
        return (String)getAttributeInternal(BI);
    }

    /**Sets <code>value</code> as the attribute value for Bi
     */
    public void setBi(String value) {
        setAttributeInternal(BI, value);
    }

    /**Gets the attribute value for CidadeNat, using the alias name CidadeNat
     */
    public String getCidadeNat() {
        return (String)getAttributeInternal(CIDADENAT);
    }

    /**Sets <code>value</code> as the attribute value for CidadeNat
     */
    public void setCidadeNat(String value) {
        setAttributeInternal(CIDADENAT, value);
    }

    /**Gets the attribute value for DataUltContacto, using the alias name DataUltContacto
     */
    public Date getDataUltContacto() {
        return (Date)getAttributeInternal(DATAULTCONTACTO);
    }

    /**Sets <code>value</code> as the attribute value for DataUltContacto
     */
    public void setDataUltContacto(Date value) {
        setAttributeInternal(DATAULTCONTACTO, value);
    }

    /**Gets the attribute value for DtaNasc, using the alias name DtaNasc
     */
    public Date getDtaNasc() {
        return (Date)getAttributeInternal(DTANASC);
    }

    /**Sets <code>value</code> as the attribute value for DtaNasc
     */
    public void setDtaNasc(Date value) {
        setAttributeInternal(DTANASC, value);
    }

    /**Gets the attribute value for LocalidadeNat, using the alias name LocalidadeNat
     */
    public String getLocalidadeNat() {
        return (String)getAttributeInternal(LOCALIDADENAT);
    }

    /**Sets <code>value</code> as the attribute value for LocalidadeNat
     */
    public void setLocalidadeNat(String value) {
        setAttributeInternal(LOCALIDADENAT, value);
    }

    /**Gets the attribute value for Nacional, using the alias name Nacional
     */
    public String getNacional() {
        return (String)getAttributeInternal(NACIONAL);
    }

    /**Sets <code>value</code> as the attribute value for Nacional
     */
    public void setNacional(String value) {
        setAttributeInternal(NACIONAL, value);
    }

    /**Gets the attribute value for Nics, using the alias name Nics
     */
    public Number getNics() {
        return (Number)getAttributeInternal(NICS);
    }

    /**Sets <code>value</code> as the attribute value for Nics
     */
    public void setNics(Number value) {
        setAttributeInternal(NICS, value);
    }

    /**Gets the attribute value for Nif, using the alias name Nif
     */
    public Number getNif() {
        return (Number)getAttributeInternal(NIF);
    }

    /**Sets <code>value</code> as the attribute value for Nif
     */
    public void setNif(Number value) {
        setAttributeInternal(NIF, value);
    }

    /**Gets the attribute value for Nir, using the alias name Nir
     */
    public Number getNir() {
        return (Number)getAttributeInternal(NIR);
    }

    /**Sets <code>value</code> as the attribute value for Nir
     */
    public void setNir(Number value) {
        setAttributeInternal(NIR, value);
    }

    /**Gets the attribute value for Niss, using the alias name Niss
     */
    public Number getNiss() {
        return (Number)getAttributeInternal(NISS);
    }

    /**Sets <code>value</code> as the attribute value for Niss
     */
    public void setNiss(Number value) {
        setAttributeInternal(NISS, value);
    }

    /**Gets the attribute value for NomesProprios, using the alias name NomesProprios
     */
    public String getNomesProprios() {
        return (String)getAttributeInternal(NOMESPROPRIOS);
    }

    /**Sets <code>value</code> as the attribute value for NomesProprios
     */
    public void setNomesProprios(String value) {
        setAttributeInternal(NOMESPROPRIOS, value);
    }

    /**Gets the attribute value for NomesPropriosMae, using the alias name NomesPropriosMae
     */
    public String getNomesPropriosMae() {
        return (String)getAttributeInternal(NOMESPROPRIOSMAE);
    }

    /**Sets <code>value</code> as the attribute value for NomesPropriosMae
     */
    public void setNomesPropriosMae(String value) {
        setAttributeInternal(NOMESPROPRIOSMAE, value);
    }

    /**Gets the attribute value for NomesPropriosPai, using the alias name NomesPropriosPai
     */
    public String getNomesPropriosPai() {
        return (String)getAttributeInternal(NOMESPROPRIOSPAI);
    }

    /**Sets <code>value</code> as the attribute value for NomesPropriosPai
     */
    public void setNomesPropriosPai(String value) {
        setAttributeInternal(NOMESPROPRIOSPAI, value);
    }

    /**Gets the attribute value for NomeCompleto, using the alias name NomeCompleto
     */
    public String getNomeCompleto() {
        return (String)getAttributeInternal(NOMECOMPLETO);
    }

    /**Sets <code>value</code> as the attribute value for NomeCompleto
     */
    public void setNomeCompleto(String value) {
        setAttributeInternal(NOMECOMPLETO, value);
    }

    /**Gets the attribute value for NumVias, using the alias name NumVias
     */
    public Number getNumVias() {
        return (Number)getAttributeInternal(NUMVIAS);
    }

    /**Sets <code>value</code> as the attribute value for NumVias
     */
    public void setNumVias(Number value) {
        setAttributeInternal(NUMVIAS, value);
    }

    /**Gets the attribute value for RegiaoNat, using the alias name RegiaoNat
     */
    public String getRegiaoNat() {
        return (String)getAttributeInternal(REGIAONAT);
    }

    /**Sets <code>value</code> as the attribute value for RegiaoNat
     */
    public void setRegiaoNat(String value) {
        setAttributeInternal(REGIAONAT, value);
    }

    /**Gets the attribute value for RegUmic, using the alias name RegUmic
     */
    public String getRegUmic() {
        return (String)getAttributeInternal(REGUMIC);
    }

    /**Sets <code>value</code> as the attribute value for RegUmic
     */
    public void setRegUmic(String value) {
        setAttributeInternal(REGUMIC, value);
    }


    /**Gets the attribute value for ScgProfissaoId, using the alias name ScgProfissaoId
     */
    public Number getScgProfissaoId() {
        return (Number)getAttributeInternal(SCGPROFISSAOID);
    }

    /**Sets <code>value</code> as the attribute value for ScgProfissaoId
     */
    public void setScgProfissaoId(Number value) {
        setAttributeInternal(SCGPROFISSAOID, value);
    }

    /**Gets the attribute value for ScgSitprofId, using the alias name ScgSitprofId
     */
    public Number getScgSitprofId() {
        return (Number)getAttributeInternal(SCGSITPROFID);
    }

    /**Sets <code>value</code> as the attribute value for ScgSitprofId
     */
    public void setScgSitprofId(Number value) {
        setAttributeInternal(SCGSITPROFID, value);
    }

    /**Gets the attribute value for ScgTipobiId, using the alias name ScgTipobiId
     */
    public Number getScgTipobiId() {
        return (Number)getAttributeInternal(SCGTIPOBIID);
    }

    /**Sets <code>value</code> as the attribute value for ScgTipobiId
     */
    public void setScgTipobiId(Number value) {
        setAttributeInternal(SCGTIPOBIID, value);
    }

    /**Gets the attribute value for SchCdaineNacId, using the alias name SchCdaineNacId
     */
    public Number getSchCdaineNacId() {
        return (Number)getAttributeInternal(SCHCDAINENACID);
    }

    /**Sets <code>value</code> as the attribute value for SchCdaineNacId
     */
    public void setSchCdaineNacId(Number value) {
        setAttributeInternal(SCHCDAINENACID, value);
    }

    /**Gets the attribute value for SchCdaineNatId, using the alias name SchCdaineNatId
     */
    public Number getSchCdaineNatId() {
        return (Number)getAttributeInternal(SCHCDAINENATID);
    }

    /**Sets <code>value</code> as the attribute value for SchCdaineNatId
     */
    public void setSchCdaineNatId(Number value) {
        setAttributeInternal(SCHCDAINENATID, value);
    }

    /**Gets the attribute value for SchPaisNatId, using the alias name SchPaisNatId
     */
    public Number getSchPaisNatId() {
        return (Number)getAttributeInternal(SCHPAISNATID);
    }

    /**Sets <code>value</code> as the attribute value for SchPaisNatId
     */
    public void setSchPaisNatId(Number value) {
        setAttributeInternal(SCHPAISNATID, value);
    }

    /**Gets the attribute value for Sexo, using the alias name Sexo
     */
    public String getSexo() {
        return (String)getAttributeInternal(SEXO);
    }

    /**Sets <code>value</code> as the attribute value for Sexo
     */
    public void setSexo(String value) {
        setAttributeInternal(SEXO, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case APELIDOS:
            return getApelidos();
        case APELIDOSMAE:
            return getApelidosMae();
        case APELIDOSPAI:
            return getApelidosPai();
        case BI:
            return getBi();
        case CIDADENAT:
            return getCidadeNat();
        case DATAULTCONTACTO:
            return getDataUltContacto();
        case DTANASC:
            return getDtaNasc();
        case LOCALIDADENAT:
            return getLocalidadeNat();
        case NACIONAL:
            return getNacional();
        case NICS:
            return getNics();
        case NIF:
            return getNif();
        case NIR:
            return getNir();
        case NISS:
            return getNiss();
        case NOMESPROPRIOS:
            return getNomesProprios();
        case NOMESPROPRIOSMAE:
            return getNomesPropriosMae();
        case NOMESPROPRIOSPAI:
            return getNomesPropriosPai();
        case NOMECOMPLETO:
            return getNomeCompleto();
        case NUMVIAS:
            return getNumVias();
        case REGIAONAT:
            return getRegiaoNat();
        case REGUMIC:
            return getRegUmic();
        case SCGPROFISSAOID:
            return getScgProfissaoId();
        case SCGSITPROFID:
            return getScgSitprofId();
        case SCGTIPOBIID:
            return getScgTipobiId();
        case SCHCDAINENACID:
            return getSchCdaineNacId();
        case SCHCDAINENATID:
            return getSchCdaineNatId();
        case SCHPAISNATID:
            return getSchPaisNatId();
        case SEXO:
            return getSexo();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case ACTIVO:
            return getActivo();
        case SCHCDAINENATANTID:
            return getSchCdaineNatAntId();
        case CHAVE1:
            return getChave1();
        case CHAVE2:
            return getChave2();
        case APLSOLTEIRO:
            return getAplSolteiro();
        case NOMEPESQUISA:
            return getNomePesquisa();
        case SINCDMLID:
            return getSincDmlId();
        case SINCDATE:
            return getSincDate();
        case SCGNHABILITID:
            return getScgNhabilitId();
        case INSCRICAOUTENTE:
            return getInscricaoUtente();
        case ENTIDADEUTENTE:
            return getEntidadeUtente();
        case BENEFICIODOUTENTE:
            return getBeneficioDoUtente();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((DBSequence)value);
            return;
        case APELIDOS:
            setApelidos((String)value);
            return;
        case APELIDOSMAE:
            setApelidosMae((String)value);
            return;
        case APELIDOSPAI:
            setApelidosPai((String)value);
            return;
        case BI:
            setBi((String)value);
            return;
        case CIDADENAT:
            setCidadeNat((String)value);
            return;
        case DATAULTCONTACTO:
            setDataUltContacto((Date)value);
            return;
        case DTANASC:
            setDtaNasc((Date)value);
            return;
        case LOCALIDADENAT:
            setLocalidadeNat((String)value);
            return;
        case NACIONAL:
            setNacional((String)value);
            return;
        case NICS:
            setNics((Number)value);
            return;
        case NIF:
            setNif((Number)value);
            return;
        case NIR:
            setNir((Number)value);
            return;
        case NISS:
            setNiss((Number)value);
            return;
        case NOMESPROPRIOS:
            setNomesProprios((String)value);
            return;
        case NOMESPROPRIOSMAE:
            setNomesPropriosMae((String)value);
            return;
        case NOMESPROPRIOSPAI:
            setNomesPropriosPai((String)value);
            return;
        case NOMECOMPLETO:
            setNomeCompleto((String)value);
            return;
        case NUMVIAS:
            setNumVias((Number)value);
            return;
        case REGIAONAT:
            setRegiaoNat((String)value);
            return;
        case REGUMIC:
            setRegUmic((String)value);
            return;
        case SCGPROFISSAOID:
            setScgProfissaoId((Number)value);
            return;
        case SCGSITPROFID:
            setScgSitprofId((Number)value);
            return;
        case SCGTIPOBIID:
            setScgTipobiId((Number)value);
            return;
        case SCHCDAINENACID:
            setSchCdaineNacId((Number)value);
            return;
        case SCHCDAINENATID:
            setSchCdaineNatId((Number)value);
            return;
        case SCHPAISNATID:
            setSchPaisNatId((Number)value);
            return;
        case SEXO:
            setSexo((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case ACTIVO:
            setActivo((String)value);
            return;
        case SCHCDAINENATANTID:
            setSchCdaineNatAntId((Number)value);
            return;
        case CHAVE1:
            setChave1((String)value);
            return;
        case CHAVE2:
            setChave2((String)value);
            return;
        case APLSOLTEIRO:
            setAplSolteiro((String)value);
            return;
        case NOMEPESQUISA:
            setNomePesquisa((String)value);
            return;
        case SINCDMLID:
            setSincDmlId((Number)value);
            return;
        case SINCDATE:
            setSincDate((Date)value);
            return;
        case SCGNHABILITID:
            setScgNhabilitId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

//    protected void doDML(int operation, TransactionEvent transactionEvent) {
//        switch (operation)
//         {
//         case DML_UPDATE:
//
//             {
//             super.doDML(operation, transactionEvent);
//
//             }break;
//
//         case DML_DELETE:
//             {
//             super.doDML(operation, transactionEvent);
//
//             }break;
//
//         case DML_INSERT:
//             {
//             //////////////////////////////////////
//             // Pre Insert Actions //
//             /////////////////////////////////////
//             // Grab the child records before the update to the parent record.
//             
//             String tipoInscr = "T";
//             
//             if ( this.getInscricaoUtente().getRowAtRangeIndex(0) == null ) {
//                 tipoInscr = "T";
//             } else {
//                 tipoInscr = "N";
//             }
//             
//             RowIterator UpdateFilesIterator = null;
//             
//             if ( tipoInscr.equalsIgnoreCase("T") ) {
//                 UpdateFilesIterator = this.getInscricaoTempUtente();
//             } else {
//                 UpdateFilesIterator = this.getInscricaoUtente();
//             }
//             
//             RowIterator UpdateFilesIteratorMorada = this.getMoradaUtente();
//             // RowIterator UpdateFilesIteratorContacto = this.getContactoUtente();
//             
//             //this.getInscricaoUtente().setw
//             
//             //Call the super which saves the records.
//             super.doDML(operation, transactionEvent);
//             
//             //////////////////////////////////////
//             // Post Insert Actions //
//             /////////////////////////////////////
//             //If we did a insert of a work flow, and there are temp sequence numbers that need to be linked
//             //back to the parent record, this code gets the iterator and loops through the records updating the ids
//             //Create an instance of the child records.
//             
//             InscricaoUtenteImpl updateFile;
//             InscricaoTempUtenteImpl updateFileTemp;
//             
//             UpdateFilesIterator.reset();
//             //Loop throught he list of child records and update with new ID
//             while (UpdateFilesIterator.hasNext()){
//                 if ( tipoInscr.equalsIgnoreCase("T") ) {
//                     updateFileTemp = (InscricaoTempUtenteImpl) UpdateFilesIterator.next();
//                     updateFileTemp.setAttribute("IduIdentUtId", this.getId().getSequenceNumber());
//                 } else {
//                     updateFile = (InscricaoUtenteImpl) UpdateFilesIterator.next();
//                     updateFile.setAttribute("IduIdentUtId", this.getId().getSequenceNumber());
//                 }
//                 
//             }
//             
//             /*MoradaUtenteImpl updateFileMorada;
//             
//             UpdateFilesIteratorMorada.reset();
//             //Loop throught he list of child records and update with new ID
//             while (UpdateFilesIteratorMorada.hasNext()){
//                 updateFileMorada = (MoradaUtenteImpl) UpdateFilesIteratorMorada.next();
//                 updateFileMorada.setAttribute("IduIdentUtId", this.getId().getSequenceNumber());
//             }
//             
//             ContactoUtenteImpl updateFileContacto;
//             
//             UpdateFilesIteratorContacto.reset();
//             //Loop throught he list of child records and update with new ID
//             while (UpdateFilesIteratorContacto.hasNext()){
//                 updateFileContacto = (ContactoUtenteImpl) UpdateFilesIteratorContacto.next();
//                 updateFileContacto.setAttribute("IduIdentUtId", this.getId().getSequenceNumber());
//             }*/
//                 
//             }break;
//
//         }
//    }


    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }


    /**Gets the attribute value for Activo, using the alias name Activo
     */
    public String getActivo() {
        return (String)getAttributeInternal(ACTIVO);
    }

    /**Sets <code>value</code> as the attribute value for Activo
     */
    public void setActivo(String value) {
        setAttributeInternal(ACTIVO, value);
    }

    /**Gets the attribute value for SchCdaineNatAntId, using the alias name SchCdaineNatAntId
     */
    public Number getSchCdaineNatAntId() {
        return (Number)getAttributeInternal(SCHCDAINENATANTID);
    }

    /**Sets <code>value</code> as the attribute value for SchCdaineNatAntId
     */
    public void setSchCdaineNatAntId(Number value) {
        setAttributeInternal(SCHCDAINENATANTID, value);
    }

    /**Gets the attribute value for Chave1, using the alias name Chave1
     */
    public String getChave1() {
        return (String)getAttributeInternal(CHAVE1);
    }

    /**Sets <code>value</code> as the attribute value for Chave1
     */
    public void setChave1(String value) {
        setAttributeInternal(CHAVE1, value);
    }

    /**Gets the attribute value for Chave2, using the alias name Chave2
     */
    public String getChave2() {
        return (String)getAttributeInternal(CHAVE2);
    }

    /**Sets <code>value</code> as the attribute value for Chave2
     */
    public void setChave2(String value) {
        setAttributeInternal(CHAVE2, value);
    }


    /**Gets the attribute value for AplSolteiro, using the alias name AplSolteiro
     */
    public String getAplSolteiro() {
        return (String)getAttributeInternal(APLSOLTEIRO);
    }

    /**Sets <code>value</code> as the attribute value for AplSolteiro
     */
    public void setAplSolteiro(String value) {
        setAttributeInternal(APLSOLTEIRO, value);
    }

    /**Gets the attribute value for NomePesquisa, using the alias name NomePesquisa
     */
    public String getNomePesquisa() {
        return (String)getAttributeInternal(NOMEPESQUISA);
    }

    /**Sets <code>value</code> as the attribute value for NomePesquisa
     */
    public void setNomePesquisa(String value) {
        setAttributeInternal(NOMEPESQUISA, value);
    }

    /**Gets the attribute value for SincDmlId, using the alias name SincDmlId
     */
    public Number getSincDmlId() {
        return (Number)getAttributeInternal(SINCDMLID);
    }

    /**Sets <code>value</code> as the attribute value for SincDmlId
     */
    public void setSincDmlId(Number value) {
        setAttributeInternal(SINCDMLID, value);
    }

    /**Gets the attribute value for SincDate, using the alias name SincDate
     */
    public Date getSincDate() {
        return (Date)getAttributeInternal(SINCDATE);
    }

    /**Sets <code>value</code> as the attribute value for SincDate
     */
    public void setSincDate(Date value) {
        setAttributeInternal(SINCDATE, value);
    }

    /**Gets the attribute value for ScgNhabilitId, using the alias name ScgNhabilitId
     */
    public Number getScgNhabilitId() {
        return (Number)getAttributeInternal(SCGNHABILITID);
    }

    /**Sets <code>value</code> as the attribute value for ScgNhabilitId
     */
    public void setScgNhabilitId(Number value) {
        setAttributeInternal(SCGNHABILITID, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getInscricaoUtente() {
        return (RowIterator)getAttributeInternal(INSCRICAOUTENTE);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getEntidadeUtente() {
        return (RowIterator)getAttributeInternal(ENTIDADEUTENTE);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getBeneficioDoUtente() {
        return (RowIterator)getAttributeInternal(BENEFICIODOUTENTE);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }
    
}