package ora.pt.cons.igif.sics;

import ora.pt.cons.igif.sics.ViewObjectImpl;
import ora.pt.cons.igif.sics.common.InformacaoUtente;

import ora.pt.cons.igif.sics.utentes.IdentificacaoUtenteModuleImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.TransactionEvent;

import org.apache.log4j.Logger;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InformacaoUtenteImpl extends ViewObjectImpl implements InformacaoUtente {
    
    private static Logger log = Logger.getLogger(InformacaoUtenteImpl.class);
    
    /**This is the default constructor (do not remove)
     */
    public InformacaoUtenteImpl() {
    }

    /**Gets the bind variable value for idUtente
     */
    public Number getidUtente() {
        return (Number)getNamedWhereClauseParam("idUtente");
    }

    /**Sets <code>value</code> for bind variable idUtente
     */
    public void setidUtente(Number value) {
        setNamedWhereClauseParam("idUtente", value);
    }

    /**Gets the bind variable value for nomeUtente
     */
    public String getnomeUtente() {
        return (String)getNamedWhereClauseParam("nomeUtente");
    }

    /**Sets <code>value</code> for bind variable nomeUtente
     */
    public void setnomeUtente(String value) {
        setNamedWhereClauseParam("nomeUtente", value);
    }

    /**Gets the bind variable value for numUtente
     */
    public Number getnumUtente() {
        return (Number)getNamedWhereClauseParam("numUtente");
    }

    /**Sets <code>value</code> for bind variable numUtente
     */
    public void setnumUtente(Number value) {
        setNamedWhereClauseParam("numUtente", value);
    }


    /**Gets the bind variable value for numSSocial
     */
    public Number getnumSSocial() {
        return (Number)getNamedWhereClauseParam("numSSocial");
    }

    /**Sets <code>value</code> for bind variable numSSocial
     */
    public void setnumSSocial(Number value) {
        setNamedWhereClauseParam("numSSocial", value);
    }

    /**Gets the bind variable value for entResp
     */
    public String getentResp() {
        return (String)getNamedWhereClauseParam("entResp");
    }

    /**Sets <code>value</code> for bind variable entResp
     */
    public void setentResp(String value) {
        setNamedWhereClauseParam("entResp", value);
    }

    /**Gets the bind variable value for numBI
     */
    public String getnumBI() {
        return (String)getNamedWhereClauseParam("numBI");
    }

    /**Sets <code>value</code> for bind variable numBI
     */
    public void setnumBI(String value) {
        setNamedWhereClauseParam("numBI", value);
    }


    /**Gets the bind variable value for dataNascimento
     */
    public String getdataNascimento() {
        return (String)getNamedWhereClauseParam("dataNascimento");
    }

    /**Sets <code>value</code> for bind variable dataNascimento
     */
    public void setdataNascimento(String value) {
        setNamedWhereClauseParam("dataNascimento", value);
    }

    /**Gets the bind variable value for idHistEntUtente
     */
    public Number getidHistEntUtente() {
        return (Number)getNamedWhereClauseParam("idHistEntUtente");
    }

    /**Sets <code>value</code> for bind variable idHistEntUtente
     */
    public void setidHistEntUtente(Number value) {
        setNamedWhereClauseParam("idHistEntUtente", value);
    }

    /**Gets the bind variable value for numBeneficiario
     */
    public String getnumBeneficiario() {
        return (String)getNamedWhereClauseParam("numBeneficiario");
    }

    /**Sets <code>value</code> for bind variable numBeneficiario
     */
    public void setnumBeneficiario(String value) {
        setNamedWhereClauseParam("numBeneficiario", value);
    }

    /**Gets the bind variable value for entRespAbrv
     */
    public String getentRespAbrv() {
        return (String)getNamedWhereClauseParam("entRespAbrv");
    }

    /**Sets <code>value</code> for bind variable entRespAbrv
     */
    public void setentRespAbrv(String value) {
        setNamedWhereClauseParam("entRespAbrv", value);
    }
    
    public void beforeRollback(TransactionEvent transactionEvent) {
        // -- 24.04.2008 comentado para que em caso de rollback o estado da ViewObject seja mantido
        // super.beforeRollback(transactionEvent);
    }

    public void afterRollback(TransactionEvent transactionEvent) {
        // -- 24.04.2008 comentado para que em caso de rollback o estado da ViewObject seja mantido
        // super.afterRollback(transactionEvent);
    }
    
    public boolean isUtenteSelected() {
        if (this.getCurrentRow() != null && this.getCurrentRow().getAttribute("Idutente") != null && this.getCurrentRow().getAttribute("Idutente").toString().compareTo("-1") != 0) {
            return true;
        }
        return false;
    }

    /**Gets the bind variable value for sexoUtente
     */
    public String getsexoUtente() {
        return (String)getNamedWhereClauseParam("sexoUtente");
    }

    /**Sets <code>value</code> for bind variable sexoUtente
     */
    public void setsexoUtente(String value) {
        setNamedWhereClauseParam("sexoUtente", value);
    }
    
    public void updateNissUtente (Number novoNiss) {
    /*
        try {
        
            //update InformacaoUtente ViewObject
            
            this.setnumSSocial(novoNiss);
            this.executeQuery();
        
            //update DataBase
            Number idUtente = this.getidUtente();
            RootAppModuleImpl rootApp = (RootAppModuleImpl)this.getApplicationModule();
            IdentificacaoUtenteModuleImpl utenteApp = (IdentificacaoUtenteModuleImpl)rootApp.getIdentificacaoUtenteModule();
            IdentificacoesUtenteImpl utenteEntity =  utenteApp.getIdentificacoesUtente();
            
            Key rowKey = new Key(new Object[] { idUtente });
            Row[] rows = utenteEntity.findByKey(rowKey, 1);
            IdentificacoesUtenteRowImpl row = null;
            for (int i = 0; i < rows.length; i++) {
                row = (IdentificacoesUtenteRowImpl)rows[i];
                row.setNiss(novoNiss);
            }
            
        }catch(Exception e) {
            log.error(e);
            this.getDBTransaction().rollback();
        }
        this.getDBTransaction().commit();
        */
    }


    /**Gets the bind variable value for nomeToNormal
     */
    public String getnomeToNormal() {
        return (String)getNamedWhereClauseParam("nomeToNormal");
    }

    /**Sets <code>value</code> for bind variable nomeToNormal
     */
    public void setnomeToNormal(String value) {
        setNamedWhereClauseParam("nomeToNormal", value);
    }
}
