package ora.pt.cons.igif.sics.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface InformacaoUtente extends ViewObject {
    void afterRollback(TransactionEvent transactionEvent);

    void beforeRollback(TransactionEvent transactionEvent);

    void clearWhereState();

    long getEstimatedRowCount();

    String getentResp();

    String getentRespAbrv();

    Number getidHistEntUtente();

    Number getidUtente();

    String getnomeUtente();

    String getnumBI();

    String getnumBeneficiario();

    Number getnumSSocial();

    Number getnumUtente();

    boolean isUtenteSelected();

    void setentResp(String value);

    void setentRespAbrv(String value);

    void setidHistEntUtente(Number value);

    void setidUtente(Number value);

    void setnomeUtente(String value);

    void setnumBI(String value);

    void setnumBeneficiario(String value);

    void setnumSSocial(Number value);

    void setnumUtente(Number value);

    void updateNissUtente(Number novoNiss);

    String getdataNascimento();

    void setdataNascimento(String value);

    String getsexoUtente();

    void setsexoUtente(String value);
}
