package ora.pt.cons.igif.sics.utentes.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class ListaBeneficiosDoUtenteRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "DtaValidade_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataFim_LABEL", "Data Fim" },
{ "DataIni_LABEL", "Data Início" },
{ "DtaValidade_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataFim_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "Descr_LABEL", "Motivo" },
{ "DataFim_FMT_FORMAT", "dd-MM-yyyy" },
{ "DataIni_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DataIni_FMT_FORMAT", "dd-MM-yyyy" },
{ "DtaValidade_LABEL", "Data Validade" }};

    /**This is the default constructor (do not remove)
     */
    public ListaBeneficiosDoUtenteRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
