package ora.pt.cons.igif.sics;

import ora.pt.cons.igif.sics.common.ListaParametrosRow;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaParametrosRowImpl extends ViewRowImpl implements ListaParametrosRow {
    public static final int NOME = 0;
    public static final int VALTEXT = 1;
    public static final int VALNUMBER = 2;
    public static final int VALDATE = 3;

    /**This is the default constructor (do not remove)
     */
    public ListaParametrosRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Nome
     */
    public String getNome() {
        return (String) getAttributeInternal(NOME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nome
     */
    public void setNome(String value) {
        setAttributeInternal(NOME, value);
    }

    /**Gets the attribute value for the calculated attribute ValText
     */
    public String getValText() {
        return (String) getAttributeInternal(VALTEXT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ValText
     */
    public void setValText(String value) {
        setAttributeInternal(VALTEXT, value);
    }

    /**Gets the attribute value for the calculated attribute ValNumber
     */
    public Number getValNumber() {
        return (Number) getAttributeInternal(VALNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ValNumber
     */
    public void setValNumber(Number value) {
        setAttributeInternal(VALNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute ValDate
     */
    public Date getValDate() {
        return (Date) getAttributeInternal(VALDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ValDate
     */
    public void setValDate(Date value) {
        setAttributeInternal(VALDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case NOME:
            return getNome();
        case VALTEXT:
            return getValText();
        case VALNUMBER:
            return getValNumber();
        case VALDATE:
            return getValDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case VALNUMBER:
            setValNumber((Number)value);
            return;
        case VALDATE:
            setValDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
