package ora.pt.cons.igif.sics.utentes;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaBeneficiosDoUtenteRowImpl extends ViewRowImpl {
    public static final int IHBID = 0;
    public static final int IDUIDENTUTID = 1;
    public static final int IDUBENEFUTID = 2;
    public static final int DESCRABREV = 3;
    public static final int DESCR = 4;
    public static final int NDOCISENT = 5;
    public static final int DATAINI = 6;
    public static final int DATAFIM = 7;
    public static final int DTAVALIDADE = 8;
    public static final int IDBENEF = 9;
    public static final int CODBENEF = 10;
    public static final int DESCBENEF = 11;
    public static final int EXPIRADO = 12;

    /**This is the default constructor (do not remove)
     */
    public ListaBeneficiosDoUtenteRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute IhbId
     */
    public Number getIhbId() {
        return (Number) getAttributeInternal(IHBID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IhbId
     */
    public void setIhbId(Number value) {
        setAttributeInternal(IHBID, value);
    }

    /**Gets the attribute value for the calculated attribute IduIdentUtId
     */
    public Number getIduIdentUtId() {
        return (Number) getAttributeInternal(IDUIDENTUTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IduIdentUtId
     */
    public void setIduIdentUtId(Number value) {
        setAttributeInternal(IDUIDENTUTID, value);
    }

    /**Gets the attribute value for the calculated attribute DescrAbrev
     */
    public String getDescrAbrev() {
        return (String) getAttributeInternal(DESCRABREV);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DescrAbrev
     */
    public void setDescrAbrev(String value) {
        setAttributeInternal(DESCRABREV, value);
    }

    /**Gets the attribute value for the calculated attribute Descr
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Descr
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**Gets the attribute value for the calculated attribute NdocIsent
     */
    public Number getNdocIsent() {
        return (Number) getAttributeInternal(NDOCISENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NdocIsent
     */
    public void setNdocIsent(Number value) {
        setAttributeInternal(NDOCISENT, value);
    }

    /**Gets the attribute value for the calculated attribute DataIni
     */
    public Date getDataIni() {
        return (Date) getAttributeInternal(DATAINI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataIni
     */
    public void setDataIni(Date value) {
        setAttributeInternal(DATAINI, value);
    }

    /**Gets the attribute value for the calculated attribute DataFim
     */
    public Date getDataFim() {
        return (Date) getAttributeInternal(DATAFIM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataFim
     */
    public void setDataFim(Date value) {
        setAttributeInternal(DATAFIM, value);
    }

    /**Gets the attribute value for the calculated attribute DtaValidade
     */
    public Date getDtaValidade() {
        return (Date) getAttributeInternal(DTAVALIDADE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DtaValidade
     */
    public void setDtaValidade(Date value) {
        setAttributeInternal(DTAVALIDADE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IHBID:
            return getIhbId();
        case IDUIDENTUTID:
            return getIduIdentUtId();
        case IDUBENEFUTID:
            return getIduBenefUtId();
        case DESCRABREV:
            return getDescrAbrev();
        case DESCR:
            return getDescr();
        case NDOCISENT:
            return getNdocIsent();
        case DATAINI:
            return getDataIni();
        case DATAFIM:
            return getDataFim();
        case DTAVALIDADE:
            return getDtaValidade();
        case IDBENEF:
            return getIdBenef();
        case CODBENEF:
            return getCodBenef();
        case DESCBENEF:
            return getDescBenef();
        case EXPIRADO:
            return getExpirado();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IHBID:
            setIhbId((Number)value);
            return;
        case IDUIDENTUTID:
            setIduIdentUtId((Number)value);
            return;
        case IDUBENEFUTID:
            setIduBenefUtId((Number)value);
            return;
        case DESCRABREV:
            setDescrAbrev((String)value);
            return;
        case DESCR:
            setDescr((String)value);
            return;
        case NDOCISENT:
            setNdocIsent((Number)value);
            return;
        case DATAINI:
            setDataIni((Date)value);
            return;
        case DATAFIM:
            setDataFim((Date)value);
            return;
        case DTAVALIDADE:
            setDtaValidade((Date)value);
            return;
        case IDBENEF:
            setIdBenef((Number)value);
            return;
        case CODBENEF:
            setCodBenef((String)value);
            return;
        case DESCBENEF:
            setDescBenef((String)value);
            return;
        case EXPIRADO:
            setExpirado((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute CodBenef
     */
    public String getCodBenef() {
        return (String) getAttributeInternal(CODBENEF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodBenef
     */
    public void setCodBenef(String value) {
        setAttributeInternal(CODBENEF, value);
    }

    /**Gets the attribute value for the calculated attribute DescBenef
     */
    public String getDescBenef() {
        return (String) getAttributeInternal(DESCBENEF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DescBenef
     */
    public void setDescBenef(String value) {
        setAttributeInternal(DESCBENEF, value);
    }

    /**Gets the attribute value for the calculated attribute IdBenef
     */
    public Number getIdBenef() {
        return (Number) getAttributeInternal(IDBENEF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdBenef
     */
    public void setIdBenef(Number value) {
        setAttributeInternal(IDBENEF, value);
    }

    /**Gets the attribute value for the calculated attribute IduBenefUtId
     */
    public Number getIduBenefUtId() {
        return (Number) getAttributeInternal(IDUBENEFUTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IduBenefUtId
     */
    public void setIduBenefUtId(Number value) {
        setAttributeInternal(IDUBENEFUTID, value);
    }

    /**Gets the attribute value for the calculated attribute Expirado
     */
    public String getExpirado() {
        return (String) getAttributeInternal(EXPIRADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Expirado
     */
    public void setExpirado(String value) {
        setAttributeInternal(EXPIRADO, value);
    }
}
