package ora.pt.cons.igif.sics.suporte;

import ora.pt.cons.igif.sics.suporte.common.ListaEntidadesResponsaveisRow;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaEntidadesResponsaveisRowImpl extends ViewRowImpl implements ListaEntidadesResponsaveisRow {
    public static final int NUMBENEF = 0;
    public static final int CARTAO = 1;
    public static final int ENTDEFAULT = 2;
    public static final int DESIGNACAO = 3;
    public static final int ID = 4;
    public static final int IDUIDENTUTID = 5;
    public static final int CODIGO = 6;
    public static final int DESCRABVR = 7;
    public static final int SYSENTIDADESID = 8;
    public static final int ORDEM = 9;
    public static final int EXPIRADO = 10;
    public static final int DTAVAL = 11;

    /**This is the default constructor (do not remove)
     */
    public ListaEntidadesResponsaveisRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Numbenef
     */
    public String getNumbenef() {
        return (String) getAttributeInternal(NUMBENEF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Numbenef
     */
    public void setNumbenef(String value) {
        setAttributeInternal(NUMBENEF, value);
    }

    /**Gets the attribute value for the calculated attribute Cartao
     */
    public String getCartao() {
        return (String) getAttributeInternal(CARTAO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cartao
     */
    public void setCartao(String value) {
        setAttributeInternal(CARTAO, value);
    }

    /**Gets the attribute value for the calculated attribute EntDefault
     */
    public String getEntDefault() {
        return (String) getAttributeInternal(ENTDEFAULT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EntDefault
     */
    public void setEntDefault(String value) {
        setAttributeInternal(ENTDEFAULT, value);
    }

    /**Gets the attribute value for the calculated attribute Designacao
     */
    public String getDesignacao() {
        return (String) getAttributeInternal(DESIGNACAO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Designacao
     */
    public void setDesignacao(String value) {
        setAttributeInternal(DESIGNACAO, value);
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for the calculated attribute IduIdentUtId
     */
    public Number getIduIdentUtId() {
        return (Number) getAttributeInternal(IDUIDENTUTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IduIdentUtId
     */
    public void setIduIdentUtId(Number value) {
        setAttributeInternal(IDUIDENTUTID, value);
    }

    /**Gets the attribute value for the calculated attribute Codigo
     */
    public String getCodigo() {
        return (String) getAttributeInternal(CODIGO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codigo
     */
    public void setCodigo(String value) {
        setAttributeInternal(CODIGO, value);
    }

    /**Gets the attribute value for the calculated attribute DescrAbvr
     */
    public String getDescrAbvr() {
        return (String) getAttributeInternal(DESCRABVR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DescrAbvr
     */
    public void setDescrAbvr(String value) {
        setAttributeInternal(DESCRABVR, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case NUMBENEF:
            return getNumbenef();
        case CARTAO:
            return getCartao();
        case ENTDEFAULT:
            return getEntDefault();
        case DESIGNACAO:
            return getDesignacao();
        case ID:
            return getId();
        case IDUIDENTUTID:
            return getIduIdentUtId();
        case CODIGO:
            return getCodigo();
        case DESCRABVR:
            return getDescrAbvr();
        case SYSENTIDADESID:
            return getSysEntidadesId();
        case ORDEM:
            return getOrdem();
        case EXPIRADO:
            return getExpirado();
        case DTAVAL:
            return getDtaVal();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CARTAO:
            setCartao((String)value);
            return;
        case ID:
            setId((Number)value);
            return;
        case IDUIDENTUTID:
            setIduIdentUtId((Number)value);
            return;
        case CODIGO:
            setCodigo((String)value);
            return;
        case DESCRABVR:
            setDescrAbvr((String)value);
            return;
        case SYSENTIDADESID:
            setSysEntidadesId((Number)value);
            return;
        case ORDEM:
            setOrdem((Number)value);
            return;
        case EXPIRADO:
            setExpirado((String)value);
            return;
        case DTAVAL:
            setDtaVal((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute SysEntidadesId
     */
    public Number getSysEntidadesId() {
        return (Number) getAttributeInternal(SYSENTIDADESID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SysEntidadesId
     */
    public void setSysEntidadesId(Number value) {
        setAttributeInternal(SYSENTIDADESID, value);
    }

    /**Gets the attribute value for the calculated attribute Ordem
     */
    public Number getOrdem() {
        return (Number) getAttributeInternal(ORDEM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Ordem
     */
    public void setOrdem(Number value) {
        setAttributeInternal(ORDEM, value);
    }

    /**Gets the attribute value for the calculated attribute Expirado
     */
    public String getExpirado() {
        return (String) getAttributeInternal(EXPIRADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Expirado
     */
    public void setExpirado(String value) {
        setAttributeInternal(EXPIRADO, value);
    }

    /**Gets the attribute value for the calculated attribute DtaVal
     */
    public Date getDtaVal() {
        return (Date) getAttributeInternal(DTAVAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DtaVal
     */
    public void setDtaVal(Date value) {
        setAttributeInternal(DTAVAL, value);
    }
}
