package ora.pt.cons.igif.sics.baixas;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaItemsBaixasRowImpl extends ViewRowImpl {
    public static final int ID = 0;
    public static final int GITBAIXASID = 1;
    public static final int NOMEFAMILIAR = 2;
    public static final int PARENTESCO = 3;
    public static final int IDPARENTESCO = 4;
    public static final int OUTROGRAUPARENTESCO = 5;
    public static final int NISSFAMILIAR = 6;
    public static final int DTANASCFAMILIAR = 7;
    public static final int IDIDENTUTIDFFAMILIAR = 8;
    public static final int TIPOREGISTO = 9;
    public static final int CODIGOITEMBAIXA = 10;
    public static final int CLASSDOENCA = 11;
    public static final int IDCLASSDOENCA = 12;
    public static final int CODCLASSDOENCA = 13;
    public static final int DATAINICIO = 14;
    public static final int DATATERMO = 15;
    public static final int INCAPACITADO = 16;
    public static final int CUIDADOSINADIAVEIS = 17;
    public static final int INTERNAMENTO = 18;
    public static final int AUTORIZSAIDA = 19;
    public static final int JUSTIFICACAO = 20;
    public static final int ENTIDADE = 21;
    public static final int MEDICO = 22;
    public static final int DIASDIFERENCA = 23;
    public static final int DATACRIACAO = 24;
    public static final int ALTAENVIADA = 25;
    public static final int CIRURGIAAMBULATORIO = 26;
    public static final int NISSPROGENITOR = 27;
    public static final int NISSUTENTE = 28;
    public static final int NUMBENEFUTENTE = 29;
    public static final int DIASBAIXA = 30;

    /**This is the default constructor (do not remove)
     */
    public ListaItemsBaixasRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for the calculated attribute Gitbaixasid
     */
    public Number getGitbaixasid() {
        return (Number) getAttributeInternal(GITBAIXASID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Gitbaixasid
     */
    public void setGitbaixasid(Number value) {
        setAttributeInternal(GITBAIXASID, value);
    }

    /**Gets the attribute value for the calculated attribute Nomefamiliar
     */
    public String getNomefamiliar() {
        return (String) getAttributeInternal(NOMEFAMILIAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomefamiliar
     */
    public void setNomefamiliar(String value) {
        setAttributeInternal(NOMEFAMILIAR, value);
    }

    /**Gets the attribute value for the calculated attribute Parentesco
     */
    public String getParentesco() {
        return (String) getAttributeInternal(PARENTESCO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Parentesco
     */
    public void setParentesco(String value) {
        setAttributeInternal(PARENTESCO, value);
    }

    /**Gets the attribute value for the calculated attribute Idparentesco
     */
    public Number getIdparentesco() {
        return (Number) getAttributeInternal(IDPARENTESCO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Idparentesco
     */
    public void setIdparentesco(Number value) {
        setAttributeInternal(IDPARENTESCO, value);
    }

    /**Gets the attribute value for the calculated attribute Outrograuparentesco
     */
    public String getOutrograuparentesco() {
        return (String) getAttributeInternal(OUTROGRAUPARENTESCO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Outrograuparentesco
     */
    public void setOutrograuparentesco(String value) {
        setAttributeInternal(OUTROGRAUPARENTESCO, value);
    }

    /**Gets the attribute value for the calculated attribute Nissfamiliar
     */
    public Number getNissfamiliar() {
        return (Number) getAttributeInternal(NISSFAMILIAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nissfamiliar
     */
    public void setNissfamiliar(Number value) {
        setAttributeInternal(NISSFAMILIAR, value);
    }

    /**Gets the attribute value for the calculated attribute Dtanascfamiliar
     */
    public Date getDtanascfamiliar() {
        return (Date) getAttributeInternal(DTANASCFAMILIAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Dtanascfamiliar
     */
    public void setDtanascfamiliar(Date value) {
        setAttributeInternal(DTANASCFAMILIAR, value);
    }

    /**Gets the attribute value for the calculated attribute Ididentutidffamiliar
     */
    public Number getIdidentutidffamiliar() {
        return (Number) getAttributeInternal(IDIDENTUTIDFFAMILIAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Ididentutidffamiliar
     */
    public void setIdidentutidffamiliar(Number value) {
        setAttributeInternal(IDIDENTUTIDFFAMILIAR, value);
    }

    /**Gets the attribute value for the calculated attribute Tiporegisto
     */
    public String getTiporegisto() {
        return (String) getAttributeInternal(TIPOREGISTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tiporegisto
     */
    public void setTiporegisto(String value) {
        setAttributeInternal(TIPOREGISTO, value);
    }

    /**Gets the attribute value for the calculated attribute Codigoitembaixa
     */
    public String getCodigoitembaixa() {
        return (String) getAttributeInternal(CODIGOITEMBAIXA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codigoitembaixa
     */
    public void setCodigoitembaixa(String value) {
        setAttributeInternal(CODIGOITEMBAIXA, value);
    }

    /**Gets the attribute value for the calculated attribute Classdoenca
     */
    public String getClassdoenca() {
        return (String) getAttributeInternal(CLASSDOENCA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Classdoenca
     */
    public void setClassdoenca(String value) {
        setAttributeInternal(CLASSDOENCA, value);
    }

    /**Gets the attribute value for the calculated attribute Idclassdoenca
     */
    public Number getIdclassdoenca() {
        return (Number) getAttributeInternal(IDCLASSDOENCA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Idclassdoenca
     */
    public void setIdclassdoenca(Number value) {
        setAttributeInternal(IDCLASSDOENCA, value);
    }

    /**Gets the attribute value for the calculated attribute Codclassdoenca
     */
    public String getCodclassdoenca() {
        return (String) getAttributeInternal(CODCLASSDOENCA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codclassdoenca
     */
    public void setCodclassdoenca(String value) {
        setAttributeInternal(CODCLASSDOENCA, value);
    }

    /**Gets the attribute value for the calculated attribute Datainicio
     */
    public Date getDatainicio() {
        return (Date) getAttributeInternal(DATAINICIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Datainicio
     */
    public void setDatainicio(Date value) {
        setAttributeInternal(DATAINICIO, value);
    }

    /**Gets the attribute value for the calculated attribute Datatermo
     */
    public Date getDatatermo() {
        return (Date) getAttributeInternal(DATATERMO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Datatermo
     */
    public void setDatatermo(Date value) {
        setAttributeInternal(DATATERMO, value);
    }

    /**Gets the attribute value for the calculated attribute Incapacitado
     */
    public String getIncapacitado() {
        return (String) getAttributeInternal(INCAPACITADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Incapacitado
     */
    public void setIncapacitado(String value) {
        setAttributeInternal(INCAPACITADO, value);
    }

    /**Gets the attribute value for the calculated attribute Cuidadosinadiaveis
     */
    public String getCuidadosinadiaveis() {
        return (String) getAttributeInternal(CUIDADOSINADIAVEIS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cuidadosinadiaveis
     */
    public void setCuidadosinadiaveis(String value) {
        setAttributeInternal(CUIDADOSINADIAVEIS, value);
    }

    /**Gets the attribute value for the calculated attribute Internamento
     */
    public String getInternamento() {
        return (String) getAttributeInternal(INTERNAMENTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Internamento
     */
    public void setInternamento(String value) {
        setAttributeInternal(INTERNAMENTO, value);
    }

    /**Gets the attribute value for the calculated attribute Autorizsaida
     */
    public String getAutorizsaida() {
        return (String) getAttributeInternal(AUTORIZSAIDA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Autorizsaida
     */
    public void setAutorizsaida(String value) {
        setAttributeInternal(AUTORIZSAIDA, value);
    }

    /**Gets the attribute value for the calculated attribute Justificacao
     */
    public String getJustificacao() {
        return (String) getAttributeInternal(JUSTIFICACAO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Justificacao
     */
    public void setJustificacao(String value) {
        setAttributeInternal(JUSTIFICACAO, value);
    }

    /**Gets the attribute value for the calculated attribute Entidade
     */
    public String getEntidade() {
        return (String) getAttributeInternal(ENTIDADE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Entidade
     */
    public void setEntidade(String value) {
        setAttributeInternal(ENTIDADE, value);
    }

    /**Gets the attribute value for the calculated attribute Medico
     */
    public String getMedico() {
        return (String) getAttributeInternal(MEDICO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Medico
     */
    public void setMedico(String value) {
        setAttributeInternal(MEDICO, value);
    }

    /**Gets the attribute value for the calculated attribute Diasdiferenca
     */
    public Number getDiasdiferenca() {
        return (Number) getAttributeInternal(DIASDIFERENCA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Diasdiferenca
     */
    public void setDiasdiferenca(Number value) {
        setAttributeInternal(DIASDIFERENCA, value);
    }

    /**Gets the attribute value for the calculated attribute Datacriacao
     */
    public Date getDatacriacao() {
        return (Date) getAttributeInternal(DATACRIACAO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Datacriacao
     */
    public void setDatacriacao(Date value) {
        setAttributeInternal(DATACRIACAO, value);
    }

    /**Gets the attribute value for the calculated attribute Altaenviada
     */
    public String getAltaenviada() {
        return (String) getAttributeInternal(ALTAENVIADA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Altaenviada
     */
    public void setAltaenviada(String value) {
        setAttributeInternal(ALTAENVIADA, value);
    }

    /**Gets the attribute value for the calculated attribute Cirurgiaambulatorio
     */
    public String getCirurgiaambulatorio() {
        return (String) getAttributeInternal(CIRURGIAAMBULATORIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cirurgiaambulatorio
     */
    public void setCirurgiaambulatorio(String value) {
        setAttributeInternal(CIRURGIAAMBULATORIO, value);
    }

    /**Gets the attribute value for the calculated attribute Nissprogenitor
     */
    public Number getNissprogenitor() {
        return (Number) getAttributeInternal(NISSPROGENITOR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nissprogenitor
     */
    public void setNissprogenitor(Number value) {
        setAttributeInternal(NISSPROGENITOR, value);
    }

    /**Gets the attribute value for the calculated attribute Nissutente
     */
    public Number getNissutente() {
        return (Number) getAttributeInternal(NISSUTENTE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nissutente
     */
    public void setNissutente(Number value) {
        setAttributeInternal(NISSUTENTE, value);
    }

    /**Gets the attribute value for the calculated attribute NumBenefutente
     */
    public String getNumBenefutente() {
        return (String) getAttributeInternal(NUMBENEFUTENTE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumBenefutente
     */
    public void setNumBenefutente(String value) {
        setAttributeInternal(NUMBENEFUTENTE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case GITBAIXASID:
            return getGitbaixasid();
        case NOMEFAMILIAR:
            return getNomefamiliar();
        case PARENTESCO:
            return getParentesco();
        case IDPARENTESCO:
            return getIdparentesco();
        case OUTROGRAUPARENTESCO:
            return getOutrograuparentesco();
        case NISSFAMILIAR:
            return getNissfamiliar();
        case DTANASCFAMILIAR:
            return getDtanascfamiliar();
        case IDIDENTUTIDFFAMILIAR:
            return getIdidentutidffamiliar();
        case TIPOREGISTO:
            return getTiporegisto();
        case CODIGOITEMBAIXA:
            return getCodigoitembaixa();
        case CLASSDOENCA:
            return getClassdoenca();
        case IDCLASSDOENCA:
            return getIdclassdoenca();
        case CODCLASSDOENCA:
            return getCodclassdoenca();
        case DATAINICIO:
            return getDatainicio();
        case DATATERMO:
            return getDatatermo();
        case INCAPACITADO:
            return getIncapacitado();
        case CUIDADOSINADIAVEIS:
            return getCuidadosinadiaveis();
        case INTERNAMENTO:
            return getInternamento();
        case AUTORIZSAIDA:
            return getAutorizsaida();
        case JUSTIFICACAO:
            return getJustificacao();
        case ENTIDADE:
            return getEntidade();
        case MEDICO:
            return getMedico();
        case DIASDIFERENCA:
            return getDiasdiferenca();
        case DATACRIACAO:
            return getDatacriacao();
        case ALTAENVIADA:
            return getAltaenviada();
        case CIRURGIAAMBULATORIO:
            return getCirurgiaambulatorio();
        case NISSPROGENITOR:
            return getNissprogenitor();
        case NISSUTENTE:
            return getNissutente();
        case NUMBENEFUTENTE:
            return getNumBenefutente();
        case DIASBAIXA:
            return getDiasbaixa();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case GITBAIXASID:
            setGitbaixasid((Number)value);
            return;
        case NOMEFAMILIAR:
            setNomefamiliar((String)value);
            return;
        case PARENTESCO:
            setParentesco((String)value);
            return;
        case IDPARENTESCO:
            setIdparentesco((Number)value);
            return;
        case OUTROGRAUPARENTESCO:
            setOutrograuparentesco((String)value);
            return;
        case NISSFAMILIAR:
            setNissfamiliar((Number)value);
            return;
        case DTANASCFAMILIAR:
            setDtanascfamiliar((Date)value);
            return;
        case IDIDENTUTIDFFAMILIAR:
            setIdidentutidffamiliar((Number)value);
            return;
        case TIPOREGISTO:
            setTiporegisto((String)value);
            return;
        case CODIGOITEMBAIXA:
            setCodigoitembaixa((String)value);
            return;
        case CLASSDOENCA:
            setClassdoenca((String)value);
            return;
        case IDCLASSDOENCA:
            setIdclassdoenca((Number)value);
            return;
        case CODCLASSDOENCA:
            setCodclassdoenca((String)value);
            return;
        case DATAINICIO:
            setDatainicio((Date)value);
            return;
        case DATATERMO:
            setDatatermo((Date)value);
            return;
        case INCAPACITADO:
            setIncapacitado((String)value);
            return;
        case CUIDADOSINADIAVEIS:
            setCuidadosinadiaveis((String)value);
            return;
        case INTERNAMENTO:
            setInternamento((String)value);
            return;
        case AUTORIZSAIDA:
            setAutorizsaida((String)value);
            return;
        case JUSTIFICACAO:
            setJustificacao((String)value);
            return;
        case ENTIDADE:
            setEntidade((String)value);
            return;
        case MEDICO:
            setMedico((String)value);
            return;
        case DIASDIFERENCA:
            setDiasdiferenca((Number)value);
            return;
        case DATACRIACAO:
            setDatacriacao((Date)value);
            return;
        case ALTAENVIADA:
            setAltaenviada((String)value);
            return;
        case CIRURGIAAMBULATORIO:
            setCirurgiaambulatorio((String)value);
            return;
        case NISSPROGENITOR:
            setNissprogenitor((Number)value);
            return;
        case NISSUTENTE:
            setNissutente((Number)value);
            return;
        case NUMBENEFUTENTE:
            setNumBenefutente((String)value);
            return;
        case DIASBAIXA:
            setDiasbaixa((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Diasbaixa
     */
    public Number getDiasbaixa() {
        return (Number) getAttributeInternal(DIASBAIXA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Diasbaixa
     */
    public void setDiasbaixa(Number value) {
        setAttributeInternal(DIASBAIXA, value);
    }
}
