package ora.pt.cons.igif.sics.utentes.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class ListaFamiliaRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "Localidade_LABEL", "Localidade" },
{ "Procfam_LABEL", "NºProc.Fam." },
{ "CodPostal_LABEL", "Cod.Postal" },
{ "Rua_LABEL", "Rua" }};

    /**This is the default constructor (do not remove)
     */
    public ListaFamiliaRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
