package ora.pt.cons.igif.sics.utentes.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class ListaUtentesRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "IinId_LABEL", "IinId" },
{ "IiuId_LABEL", "Id Utente" },
{ "NomeCompleto_LABEL", "Nome" },
{ "Morada_LABEL", "Morada" },
{ "TipoId_LABEL", "Doc.Id." },
{ "Nir_LABEL", "Nº SNS" },
{ "Numbenef_LABEL", "Nº Beneficiário" },
{ "CsaudeCod_LABEL", "Centro de Saúde" },
{ "DtaNasc_FMT_FORMAT", "dd-MM-yyyy" },
{ "DtaNasc_LABEL", "Dt.Nasc." },
{ "Nop_LABEL", "Nº Operacional" },
{ "NumId_LABEL", "ID" },
{ "NomesProprios_LABEL", "Nomes Próprios" },
{ "Apelidos_LABEL", "Apelidos" },
{ "Niss_LABEL", "Nº SS" },
{ "Idade_LABEL", "Idade" },
{ "DtaNasc_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" }};

    /**This is the default constructor (do not remove)
     */
    public ListaUtentesRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
