package ora.pt.cons.igif.sics.baixas;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaHistBaixasRowImpl extends ViewRowImpl {
    public static final int ID = 0;
    public static final int NUMBOLETIM = 1;
    public static final int DATAINICIO = 2;
    public static final int DATAINICIOTOTAL = 3;
    public static final int DATATERMO = 4;
    public static final int CODTIPOREGISTO = 5;
    public static final int TIPOREGISTO = 6;
    public static final int ENTIDADE = 7;
    public static final int PROFISSIONAL = 8;
    public static final int DATAALTA = 9;
    public static final int MOTIVOALTA = 10;
    public static final int IDUIDENTUTID = 11;
    public static final int ANTERIORIDCLASSIFDOENCA = 12;
    public static final int IDCODASSISTENCIAFAMILIAR = 13;
    public static final int ANTERIORIDPARENTESCO = 14;
    public static final int ANTERIORNOMEFAMILIAR = 15;
    public static final int IDLASTITEMBAIXA = 16;
    public static final int HISTID = 17;
    public static final int CODIGOENTIDADEPUB = 18;
    public static final int ESTADO = 19;

    /**This is the default constructor (do not remove)
     */
    public ListaHistBaixasRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for the calculated attribute NumBoletim
     */
    public Number getNumBoletim() {
        return (Number) getAttributeInternal(NUMBOLETIM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumBoletim
     */
    public void setNumBoletim(Number value) {
        setAttributeInternal(NUMBOLETIM, value);
    }

    /**Gets the attribute value for the calculated attribute DataInicio
     */
    public Date getDataInicio() {
        return (Date) getAttributeInternal(DATAINICIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataInicio
     */
    public void setDataInicio(Date value) {
        setAttributeInternal(DATAINICIO, value);
    }

    /**Gets the attribute value for the calculated attribute DataInicioTotal
     */
    public Date getDataInicioTotal() {
        return (Date) getAttributeInternal(DATAINICIOTOTAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataInicioTotal
     */
    public void setDataInicioTotal(Date value) {
        setAttributeInternal(DATAINICIOTOTAL, value);
    }

    /**Gets the attribute value for the calculated attribute DataTermo
     */
    public Date getDataTermo() {
        return (Date) getAttributeInternal(DATATERMO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DataTermo
     */
    public void setDataTermo(Date value) {
        setAttributeInternal(DATATERMO, value);
    }

    /**Gets the attribute value for the calculated attribute Codtiporegisto
     */
    public String getCodtiporegisto() {
        return (String) getAttributeInternal(CODTIPOREGISTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codtiporegisto
     */
    public void setCodtiporegisto(String value) {
        setAttributeInternal(CODTIPOREGISTO, value);
    }

    /**Gets the attribute value for the calculated attribute Tiporegisto
     */
    public String getTiporegisto() {
        return (String) getAttributeInternal(TIPOREGISTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tiporegisto
     */
    public void setTiporegisto(String value) {
        setAttributeInternal(TIPOREGISTO, value);
    }

    /**Gets the attribute value for the calculated attribute Entidade
     */
    public String getEntidade() {
        return (String) getAttributeInternal(ENTIDADE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Entidade
     */
    public void setEntidade(String value) {
        setAttributeInternal(ENTIDADE, value);
    }

    /**Gets the attribute value for the calculated attribute Profissional
     */
    public String getProfissional() {
        return (String) getAttributeInternal(PROFISSIONAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Profissional
     */
    public void setProfissional(String value) {
        setAttributeInternal(PROFISSIONAL, value);
    }

    /**Gets the attribute value for the calculated attribute Dataalta
     */
    public Date getDataalta() {
        return (Date) getAttributeInternal(DATAALTA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Dataalta
     */
    public void setDataalta(Date value) {
        setAttributeInternal(DATAALTA, value);
    }

    /**Gets the attribute value for the calculated attribute Motivoalta
     */
    public String getMotivoalta() {
        return (String) getAttributeInternal(MOTIVOALTA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Motivoalta
     */
    public void setMotivoalta(String value) {
        setAttributeInternal(MOTIVOALTA, value);
    }

    /**Gets the attribute value for the calculated attribute IduIdentUtId
     */
    public Number getIduIdentUtId() {
        return (Number) getAttributeInternal(IDUIDENTUTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IduIdentUtId
     */
    public void setIduIdentUtId(Number value) {
        setAttributeInternal(IDUIDENTUTID, value);
    }

    /**Gets the attribute value for the calculated attribute Anterioridclassifdoenca
     */
    public Number getAnterioridclassifdoenca() {
        return (Number) getAttributeInternal(ANTERIORIDCLASSIFDOENCA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Anterioridclassifdoenca
     */
    public void setAnterioridclassifdoenca(Number value) {
        setAttributeInternal(ANTERIORIDCLASSIFDOENCA, value);
    }

    /**Gets the attribute value for the calculated attribute Idcodassistenciafamiliar
     */
    public Number getIdcodassistenciafamiliar() {
        return (Number) getAttributeInternal(IDCODASSISTENCIAFAMILIAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Idcodassistenciafamiliar
     */
    public void setIdcodassistenciafamiliar(Number value) {
        setAttributeInternal(IDCODASSISTENCIAFAMILIAR, value);
    }

    /**Gets the attribute value for the calculated attribute Anterioridparentesco
     */
    public Number getAnterioridparentesco() {
        return (Number) getAttributeInternal(ANTERIORIDPARENTESCO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Anterioridparentesco
     */
    public void setAnterioridparentesco(Number value) {
        setAttributeInternal(ANTERIORIDPARENTESCO, value);
    }

    /**Gets the attribute value for the calculated attribute Anteriornomefamiliar
     */
    public String getAnteriornomefamiliar() {
        return (String) getAttributeInternal(ANTERIORNOMEFAMILIAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Anteriornomefamiliar
     */
    public void setAnteriornomefamiliar(String value) {
        setAttributeInternal(ANTERIORNOMEFAMILIAR, value);
    }

    /**Gets the attribute value for the calculated attribute Idlastitembaixa
     */
    public Number getIdlastitembaixa() {
        return (Number) getAttributeInternal(IDLASTITEMBAIXA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Idlastitembaixa
     */
    public void setIdlastitembaixa(Number value) {
        setAttributeInternal(IDLASTITEMBAIXA, value);
    }

    /**Gets the attribute value for the calculated attribute Histid
     */
    public Number getHistid() {
        return (Number) getAttributeInternal(HISTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Histid
     */
    public void setHistid(Number value) {
        setAttributeInternal(HISTID, value);
    }

    /**Gets the attribute value for the calculated attribute Codigoentidadepub
     */
    public String getCodigoentidadepub() {
        return (String) getAttributeInternal(CODIGOENTIDADEPUB);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codigoentidadepub
     */
    public void setCodigoentidadepub(String value) {
        setAttributeInternal(CODIGOENTIDADEPUB, value);
    }

    /**Gets the attribute value for the calculated attribute Estado
     */
    public String getEstado() {
        return (String) getAttributeInternal(ESTADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Estado
     */
    public void setEstado(String value) {
        setAttributeInternal(ESTADO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case NUMBOLETIM:
            return getNumBoletim();
        case DATAINICIO:
            return getDataInicio();
        case DATAINICIOTOTAL:
            return getDataInicioTotal();
        case DATATERMO:
            return getDataTermo();
        case CODTIPOREGISTO:
            return getCodtiporegisto();
        case TIPOREGISTO:
            return getTiporegisto();
        case ENTIDADE:
            return getEntidade();
        case PROFISSIONAL:
            return getProfissional();
        case DATAALTA:
            return getDataalta();
        case MOTIVOALTA:
            return getMotivoalta();
        case IDUIDENTUTID:
            return getIduIdentUtId();
        case ANTERIORIDCLASSIFDOENCA:
            return getAnterioridclassifdoenca();
        case IDCODASSISTENCIAFAMILIAR:
            return getIdcodassistenciafamiliar();
        case ANTERIORIDPARENTESCO:
            return getAnterioridparentesco();
        case ANTERIORNOMEFAMILIAR:
            return getAnteriornomefamiliar();
        case IDLASTITEMBAIXA:
            return getIdlastitembaixa();
        case HISTID:
            return getHistid();
        case CODIGOENTIDADEPUB:
            return getCodigoentidadepub();
        case ESTADO:
            return getEstado();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
