package ora.pt.cons.igif.sics.baixas;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OperacoesLogDefImpl extends EntityDefImpl {
    /**This is the default constructor (do not remove)
     */
    public OperacoesLogDefImpl() {
    }
}
