// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package ora.pt.cons.igif.services.proxy.reenvioprocesso.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.client.ServiceExceptionImpl;
import oracle.j2ee.ws.common.util.exception.*;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class SaudeCCRespostaReenvioProcessoService_Impl extends oracle.j2ee.ws.client.BasicService implements ora.pt.cons.igif.services.proxy.reenvioprocesso.SaudeCCRespostaReenvioProcessoService {
    private static final QName serviceName = new QName("http://dynamicgateway.fsc.pt.gov.interop/", "SaudeCCRespostaReenvioProcessoService");
    private static final QName ns1_SaudeCCRespostaReenvioProcessoPort_QNAME = new QName("http://dynamicgateway.fsc.pt.gov.interop/", "SaudeCCRespostaReenvioProcessoPort");
    private static final Class saudeCCRespostaReenvioProcessoType_PortClass = ora.pt.cons.igif.services.proxy.reenvioprocesso.SaudeCCRespostaReenvioProcessoType.class;
    
    public SaudeCCRespostaReenvioProcessoService_Impl() {
        super(serviceName, new QName[] {
                        ns1_SaudeCCRespostaReenvioProcessoPort_QNAME
                    },
            new ora.pt.cons.igif.services.proxy.reenvioprocesso.runtime.SaudeCCRespostaReenvioProcessoService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(QName portName, Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_SaudeCCRespostaReenvioProcessoPort_QNAME) &&
                serviceDefInterface.equals(saudeCCRespostaReenvioProcessoType_PortClass)) {
                return getSaudeCCRespostaReenvioProcessoPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(saudeCCRespostaReenvioProcessoType_PortClass)) {
                return getSaudeCCRespostaReenvioProcessoPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public ora.pt.cons.igif.services.proxy.reenvioprocesso.SaudeCCRespostaReenvioProcessoType getSaudeCCRespostaReenvioProcessoPort() {
        String[] roles = new String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_SaudeCCRespostaReenvioProcessoPort_QNAME));
        handlerChain.setRoles(roles);
        ora.pt.cons.igif.services.proxy.reenvioprocesso.runtime.SaudeCCRespostaReenvioProcessoPortBinding_Stub stub = new ora.pt.cons.igif.services.proxy.reenvioprocesso.runtime.SaudeCCRespostaReenvioProcessoPortBinding_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
