// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.1.0, build 061008.0900.00025)

package ora.pt.cons.igif.services.proxy.identificacao.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.client.ServiceExceptionImpl;
import oracle.j2ee.ws.common.util.exception.*;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class SaudeCCRespostaIdentificarCidadaoService_Impl extends oracle.j2ee.ws.client.BasicService implements ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoService {
    private static final QName serviceName = new QName("http://dynamicgateway.fsc.pt.gov.interop/", "SaudeCCRespostaIdentificarCidadaoService");
    private static final QName ns1_SaudeCCRespostaIdentificarCidadaoPort_QNAME = new QName("http://dynamicgateway.fsc.pt.gov.interop/", "SaudeCCRespostaIdentificarCidadaoPort");
    private static final Class saudeCCRespostaIdentificarCidadaoType_PortClass = ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoType.class;
    
    public SaudeCCRespostaIdentificarCidadaoService_Impl() {
        super(serviceName, new QName[] {
                        ns1_SaudeCCRespostaIdentificarCidadaoPort_QNAME
                    },
            new ora.pt.cons.igif.services.proxy.identificacao.runtime.SaudeCCRespostaIdentificarCidadaoService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(QName portName, Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_SaudeCCRespostaIdentificarCidadaoPort_QNAME) &&
                serviceDefInterface.equals(saudeCCRespostaIdentificarCidadaoType_PortClass)) {
                return getSaudeCCRespostaIdentificarCidadaoPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(saudeCCRespostaIdentificarCidadaoType_PortClass)) {
                return getSaudeCCRespostaIdentificarCidadaoPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public ora.pt.cons.igif.services.proxy.identificacao.SaudeCCRespostaIdentificarCidadaoType getSaudeCCRespostaIdentificarCidadaoPort() {
        String[] roles = new String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_SaudeCCRespostaIdentificarCidadaoPort_QNAME));
        handlerChain.setRoles(roles);
        ora.pt.cons.igif.services.proxy.identificacao.runtime.SaudeCCRespostaIdentificarCidadaoPortBinding_Stub stub = new ora.pt.cons.igif.services.proxy.identificacao.runtime.SaudeCCRespostaIdentificarCidadaoPortBinding_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
