package ora.pt.cons.igif.services.proxy.federacao;

import java.net.URI;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

public class AttributedURI implements java.io.Serializable {
    protected java.net.URI _value;
    
    public AttributedURI() {

    }
    
    public java.net.URI get_value() {
        return _value;
    }
    
    public void set_value(java.net.URI _value) {
        this._value = _value;
    }
}