// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.1.0, build 061008.0900.00025)

package ora.pt.cons.igif.services.proxy.federacao;

import javax.xml.rpc.*;

public interface IDFedValidateWellKnownFactsResponseService extends javax.xml.rpc.Service {
    public ora.pt.cons.igif.services.proxy.federacao.IDFedValidateWellKnownFactsResponseType getIDFedValidateWellKnownFactsResponsePort() throws javax.xml.rpc.ServiceException;
}
