// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package ora.pt.cons.igif.services.proxy.reenvioprocesso;

public interface SaudeCCRespostaReenvioProcessoType extends java.rmi.Remote {
    public void saudeCCRespostaReenvioProcesso(javax.xml.soap.SOAPElement saudeCCRespostaReenvioProcessoParameters) throws 
         java.rmi.RemoteException;
}
