// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package ora.pt.cons.igif.services.proxy.reenvioprocesso;

import javax.xml.rpc.*;

public interface SaudeCCRespostaReenvioProcessoService extends javax.xml.rpc.Service {
    public ora.pt.cons.igif.services.proxy.reenvioprocesso.SaudeCCRespostaReenvioProcessoType getSaudeCCRespostaReenvioProcessoPort() throws javax.xml.rpc.ServiceException;
}
